### ISSUE TITLE
syslog image missing from Docker Hub

### ISSUE THREAD

**Issue by BenHall** [fluent/fluentd-kubernetes-daemonset#101]
```
$ docker pull fluent/fluentd-kubernetes-daemonset:syslog
Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:syslog not found
```

**Comment by repeatedly** [comment]
Provide syslog image is now on docker hub.

https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/builds/b7zigof2x6sftemqthwkckm/

We provide only debian based image because we will deprecate alpine based images.
