### ISSUE TITLE
Where is the image hosted?

### ISSUE THREAD

**Issue by gajus** [fluent/fluentd-kubernetes-daemonset#11]
The links in the README.md take to 404 page.

https://hub.docker.com/r/fluent/fluentd-kubernetes/

**Comment by gajus** [comment]
https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/

**Comment by kenden** [comment]
Or even point to the docker store:
https://store.docker.com/community/images/fluent/fluentd-kubernetes-daemonset

**Comment by alexandernilsson** [comment]
The DaemonSet yaml points to `quay.io/fluent/fluentd-kubernetes-daemonset`, which hasn't gotten updated in quite a while.

**Comment by kenden** [comment]
https://store.docker.com/community/images/fluent/fluentd-kubernetes-daemonset/tags
Last updated a month ago, it's not that bad

**Comment by kenden** [comment]
@alexandernilsson Good point, it's 3 months old. The version on dockerhub is 1 month old.
quay.io/fluent/fluentd-kubernetes-daemonset is not versioned, either, it's always 'latest'.

**Comment by so0k** [comment]
Oops, seems I introduced that mistake as we use https://hub.docker.com/r/honestbee/fluentd-kubernetes/ instead of https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/ which is also what we use in our Helm charts.

**Comment by edsiper** [comment]
Fixed,.
