### ISSUE TITLE
returned a non-zero code: 1

### ISSUE THREAD

**Issue by Allenhaozi** [fluent/fluentd-kubernetes-daemonset#111]
+ bundle config silence_root_warning true
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 2 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/fluentd/vendor/bundle/ruby/2.3.0', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/bin/bundle:22:in `<main>'
The command '/bin/sh -c set -ex     && apk upgrade --no-cache     && apk add --no-cache ruby-bundler     && apk add --no-cache --virtual .build-deps         build-base         ruby-dev         libffi-dev     && bundle config silence_root_warning true     && bundle install --gemfile=/fluentd/Gemfile --path=/fluentd/vendor/bundle     && apk del .build-deps     && gem sources --clear-all     && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem' returned a non-zero code: 1

**Comment by repeatedly** [comment]
Which image do you use? No information...

**Comment by repeatedly** [comment]
Ah, I see. Alpine's behaviour is different from debian one.
Will fix.
