### ISSUE TITLE
Close graylog section in fluent.conf.erb

### ISSUE THREAD

**Issue by miguelortize** [fluent/fluentd-kubernetes-daemonset#124]
Hi Team!
In line 158, we are not closing the graylog section, I tried to create a docker image and it kept failing, pod logs showed that this was not configured properly.

Added </match> and it helped. 

https://github.com/fluent/fluentd-kubernetes-daemonset/blob/80abc0209d013ee6d9b6ed85c41ab4cdcb6b9476/templates/conf/fluent.conf.erb#L158

**Comment by repeatedly** [comment]
Could you send a PR?

**Comment by errm** [comment]
Looks like #100 should fix this ...

**Comment by tchelovilar** [comment]
I fix this in #144
