### ISSUE TITLE
Upgrade debian-s3 image to support compress parquet

### ISSUE THREAD

**Issue by ChihSeanHsu** [fluent/fluentd-kubernetes-daemonset#1287]
As titled, latest fluent-s3-plugin supported parquet compress, just update it.
https://github.com/fluent/fluent-plugin-s3/pull/338

And it use columnify to deal with parquet.

**Comment by ChihSeanHsu** [comment]
Solved in https://github.com/fluent/fluentd-kubernetes-daemonset/pull/1286

**Comment by kenhys** [comment]
I'll release newer image.
