### ISSUE TITLE
Documentation about monitoring Fluentd daemonset with Prometheus

### ISSUE THREAD

**Issue by jcobb48** [fluent/fluentd-kubernetes-daemonset#1289]
Hi, I been researching about monitoring Fluentd daemonset using Prometheus, but documentation is not that straight forward.

Repo readme quote:
---------------------------------
Use your configuration
These images have default configuration and support some environment variables for parameters but it sometimes doesn't fit your case. If you want to use your configuration, use ConfigMap feature.

Each image has following configurations:

fluent.conf: Destination setting, Elaticsearch, kafka and etc.
kubernetes.conf: k8s specific setting. tail input for log files and kubernetes_metadata filter
tail_container_parse.conf: parser setting for /var/log/containers/*.log. See also "Use CRI parser for containerd/cri-o" logs section
prometheus.conf: prometheus plugin for fluentd monitoring
systemd.conf: systemd plugin for collecting systemd-journal log. See also "Disable systemd input" section.

---------------------------------

Could you please help me to understand prometheus.conf or point me to the documentation on how to configure prometheus and fluentd?

Should I add to prometheus.conf configmap this? https://docs.fluentd.org/monitoring-fluentd/monitoring-prometheus#step-1-counting-incoming-records-by-prometheus-filter-plugin

**Comment by kenhys** [comment]
https://github.com/fluent/fluentd-kubernetes-daemonset#use-your-configuration

section contains informative link to https://github.com/fluent/fluentd-kubernetes-daemonset/pull/349#issuecomment-579097659
