### ISSUE TITLE
Worker being OOM killed silently with info level log

### ISSUE THREAD

**Issue by siddharthck** [fluent/fluentd-kubernetes-daemonset#1295]
[](url)Hello there, 
We are using **_fluent/fluentd-kubernetes-daemonset:v1.13-debian-forward-1_** image to ship logs to [Logicmonitor](https://www.logicmonitor.com/). 

Whenever there is heavy logging, due to resource limits, we see following logs :

```
2021-08-30 09:38:44 +0000 [info]: Worker 0 finished unexpectedly with signal SIGKILL
2021-08-30 09:38:44 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2021-08-30 09:38:45 +0000 [info]: adding filter pattern="kubernetes.**" type="record_transformer"
2021-08-30 09:38:45 +0000 [info]: adding match pattern="kubernetes.**" type="lm"
2021-08-30 09:38:45 +0000 [info]: adding source type="tail"
2021-08-30 09:38:45 +0000 [info]: #0 starting fluentd worker pid=57 ppid=7 worker=0
```

This will keep on happening continuously every 2-3 minutes leading to data loss. which can be solved by increasing resource limits.

However, while troubleshooting, one would have to go through daemonset logs (with log level info) to identify issue.  

Is there an way to generate this kind of log with higher severity, or any configuration when process being OOM killed which can tell more audibly to increase resource limits?

**Comment by kenhys** [comment]
For the record, It should be fixed in serverengine side.

https://github.com/treasure-data/serverengine/blob/master/lib/serverengine/multi_process_server.rb#L145

**Comment by ashie** [comment]
> Is there an way to generate this kind of log with higher severity, or any configuration when process being OOM killed which can tell more audibly to increase resource limits?

Ah, it would be a good idea since we often receive similar issues.

e.g.) https://github.com/fluent/fluentd/issues/3413

**Comment by kenhys** [comment]
https://github.com/treasure-data/serverengine/pull/113

**Comment by ahsan13jan** [comment]
@kenhys Shouldn't it be crashing the container, so that it becomes more transparent that resources are not enough. And we'd see restarts on that pod.
