### ISSUE TITLE
Difference between kafka and kafka2 images

### ISSUE THREAD

**Issue by johnnymetz** [fluent/fluentd-kubernetes-daemonset#1299]
What's the difference between the `kafka` and `kafka2` docker images? The only difference I noticed is in the `match` directive of their `conf/fluentd.conf` files.

- https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.14/debian-kafka/conf/fluent.conf
- https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.14/debian-kafka2/conf/fluent.conf

What do these `match` differences do? Are there any other major differences? I'm trying to figure out which one to choose.

**Comment by ashie** [comment]
`kafka2` is the recommended one.
`kafka` is for Fluentd's old v0.12 API, will be removed in the future.
https://github.com/fluent/fluent-plugin-kafka#buffered-output-plugin
