### ISSUE TITLE
issues with a tag v1-debian-elasticsearch and ES 7.6.0 after upgrade on dockerhub

### ISSUE THREAD

**Issue by jekakm** [fluent/fluentd-kubernetes-daemonset#1300]
After last upgrade this tag fluentd stop working with ES 7.6.0:
#0 unexpected error error_class=Elasticsearch::UnsupportedProductError error="The client noticed that the server is not a supported distribution of Elasticsearch."

I just backup old image from old node and use that. What version I need to use now? Or I need to update ES, are there some compatible matrix? I'm confused little bit. :)

**Comment by cosmo0920** [comment]
elasticsearch-api and its related gems start to check strictly for Elasticsearch `GET /` API response since 7.14.
Could you use more detailed tags such as `v1.13-debian-elasticsearch7-1`?
