### ISSUE TITLE
Fluentd - AWS ES - Setup Fails to start the pod with FluentD v1.14.x

### ISSUE THREAD

**Issue by anand3493** [fluent/fluentd-kubernetes-daemonset#1307]
We are having an EFK stack for our logging purposes. 
Earlier we were running fluentd with the version 1.13.3 which was working fine. 
Now when I try to upgrade the fluentd to latest version that is v1.14.1, am getting the below error when the fluentd pod is getting started phase itself . 

![image](https://user-images.githubusercontent.com/90377358/135323722-a8e48e07-3ff9-4f9e-8187-c7df482d29da.png)
The same issue has been noticed even with v1.14.0 

Kindly check and let me know

**Comment by kenhys** [comment]
It seems that it is the same as  https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/74, see https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/74#issuecomment-930432543
