### ISSUE TITLE
Define syslog facility for image syslog

### ISSUE THREAD

**Issue by ADustyOldMuffin** [fluent/fluentd-kubernetes-daemonset#1317]
When using the syslog daemon set, is there any way to define the facility? From the looks of it I don't believe so.

**Comment by kenhys** [comment]
It seems that it is not intended currently.
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.14/debian-syslog/conf/fluent.conf
Thus, it will be set by default (maybe `user`?)

Best practice will depend on how to control syslog facility.
