### ISSUE TITLE
How to watch kubernetes events with fluentd

### ISSUE THREAD

**Issue by yktd26** [fluent/fluentd-kubernetes-daemonset#1318]
Hi,

I'm currently learning about using fluentd within our k8s cluster. 
Is it possible to watch kubernetes events with this daemonset deployment?
Any additional configuration need to add?

Thanks

**Comment by cosmo0920** [comment]
Hi,
Here is NOT USER FORUM.
Try to use mailing list to ask your questions.
Thanks!!
