### ISSUE TITLE
fluent-plugin-elasticsearch config options are missing

### ISSUE THREAD

**Issue by domruf** [fluent/fluentd-kubernetes-daemonset#1330]
There are quite a few configuration options from https://github.com/uken/fluent-plugin-elasticsearch#configuration missing at https://docs.fluentd.org/output/elasticsearch#parameters
The particular settings I need are ca_file, client_cert and client_key.

AFAIS the only way to use them, is to mount my own fluent.conf. But this seems wrong to me.

**Comment by kenhys** [comment]
@domruf 

Thank you for the feedback.
But in that section, it is not intended to explain the fully supported parameters.

That is why a further reading section is put on.

![image](https://user-images.githubusercontent.com/225841/150477884-3296a212-682c-467b-98af-a18e08cc18e5.png)

If you want to include the above parameters, we are welcome to your PR.
