### ISSUE TITLE
Missing newer debian-syslog releases

### ISSUE THREAD

**Issue by glpfloss** [fluent/fluentd-kubernetes-daemonset#1345]
Hi,

Im not used to open GitHub issues, so if anything is needed please let me know

We are missing newer releases for debian-syslog tag. Last tags pushed on DockerHub were on 11 Aug 2020 ( v1-debian-syslog / v1.11.2-debian-syslog-1.0 / v1.11-debian-syslog-1 )

Checking on the repo, looks like is still supported, and it should be a release available on version 1.14, please could you check?

Thanks, best regards

**Comment by L4rS6** [comment]
Hi, as mentioned [here](https://github.com/fluent/fluentd-kubernetes-daemonset#current-stable) you have to build those container images by yourself due to the following reasons:
```
As the current limitation about the number of automated builds on hub.docker.com, 
there are some restrictions to ship daemonset images:
* ... syslog images (x86_64/arm64) won't be published anymore
```

**Comment by glpfloss** [comment]
Hi,

Thank you, we didnt saw that comment, closing issue

Best regards
