### ISSUE TITLE
fluentd failed to process log after Kubernetes upgrade from 1.19.x to 1.20.x

### ISSUE THREAD

**Issue by hetian-github** [fluent/fluentd-kubernetes-daemonset#1349]
Our log system for business is EFK(elasticsearch+fluentd+kibana). The fluentd daemonset is running on AKS(Microsoft Azure Kubernetes service). I haven't done any change to the fluentd configuration. And after I upgrade the kubernetes from 1.19.x to 1.20.x, the fluentd has not sent log to Elasticsearch anymore.
From the logs of fluentd I can see it did grab logs which are located in directory /var/log/containers on kubernetes node. But then it did not send the log data to Elasticsearch. And I can see that the buffer directory is empty. When it worked well, there were buffer files written to the buffer directory.
Is there some change of Kubernetes 1.20.x that affect fluentd running?

**Comment by BenHorneIL** [comment]
What is the image of fluentd you are running and what do you have set for the conf?

we had to update 

```yaml
image: fluent/fluentd-kubernetes-daemonset:v1.4-debian-elasticsearch-1
```
to
```yaml
image: fluent/fluentd-kubernetes-daemonset:v1.12-debian-elasticsearch6-1
```
As well as update the kubernetes.conf source: 

```yaml
format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
```
