### ISSUE TITLE
BoundServiceAccountTokenVolume refresh token

### ISSUE THREAD

**Issue by tomiszili** [fluent/fluentd-kubernetes-daemonset#1361]
Hi!

I builded the latest dockerfile for papertrail, but the latest kubernetes serviceaccount 1hour expiration token can't refreshed by the image.
How can it be solved?

**Comment by hugomcfonseca** [comment]
👍 on this topic, we are now running latest version of fluentd-kubernetes-daemonset (`fluentd-kubernetes-daemonset:v1.14-debian-kafka2-1`) in EKS 1.21, and we are seeing it is using an old token in Cloudwatch logs (using this [method](https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html#identify-pods-using-stale-tokens))

**Comment by hugomcfonseca** [comment]
@ashie are there any plans for such support?

**Comment by ashie** [comment]
How about setting `/var/run/secrets/kubernetes.io/serviceaccount/token` to `bearer_token_file` of fluent-plugin-kubernetes_metadata_filter?
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter#configuration

As I described at https://github.com/ManageIQ/kubeclient/issues/561, it seems that it's already implemented, but not configured by default (the default value is `nil` in both kubeclient and fluent-plugin-kubernetes_metadata_filter).

**Comment by hugomcfonseca** [comment]
@ashie I can give it a try. But I was expecting fluentd to be already using by default as I am not setting any other configuration to ensure fluentd authenticates in Kubernetes API.

**Comment by ashie** [comment]
> @ashie I have tried with that setting, although it still appears fluentd to be reusing an old token (probably it does not refresh token as expected?).

Sorry, although it's implemented in master branch of kubeclient but not released yet.

**Comment by lcohen-11** [comment]
> > @ashie I have tried with that setting, although it still appears fluentd to be reusing an old token (probably it does not refresh token as expected?).
> 
> Sorry, although it's implemented in master branch of kubeclient, it's not released yet.

@ashie, Hi,
Do you know when will you released the fix ? thanks in advance.

**Comment by ashie** [comment]
ref: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/323

**Comment by PettitWesley** [comment]
The fix I contributed has been released: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/323#issuecomment-1165744181

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/337

**Comment by PettitWesley** [comment]
@ashie And others, please see my update above.

**Comment by ashie** [comment]
Thank you for notifying it. I'll wait your report.

**Comment by PettitWesley** [comment]
@ashie It fully works! Sorry for the alarm! 

Testing details are in the PR: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/337

**Comment by ashie** [comment]
I see, thanks for your effort!

**Comment by ashie** [comment]
Now rebuilding images...

**Comment by ashie** [comment]
Done.

**Comment by hugomcfonseca** [comment]
@ashie have you tried this? 

I used the tag `v1.14.6-debian-kafka2-1.1`, but still seems to use a token older than 1h after looking for this in cloudwatch following [this procedure](https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html#:~:text=service%20accounts.-,Service%20account%20tokens,-The%20BoundServiceAccountTokenVolume).

**Comment by ashie** [comment]
Please see #1368

**Comment by Ga13Ou** [comment]
Did the underlying kubeclient got updated? is there any way to make it refresh each hour to no longer have the **stale-token** annotation? 
If this is not the case, is there a way to test that the fix works without waiting 90 days?
