### ISSUE TITLE
Can you update fluentd-kubernetes-daemonset:v1.14-debian-opensearch-1 to include latest opensearch plugin?

### ISSUE THREAD

**Issue by amontalban** [fluent/fluentd-kubernetes-daemonset#1366]
Can you update the `fluentd-kubernetes-daemonset:v1.14-debian-opensearch-1` image to include latest OpenSearch plugin?

Thanks!

References:
- https://github.com/fluent/fluent-plugin-opensearch/releases/tag/v1.0.7
- https://github.com/fluent/fluent-plugin-opensearch/pull/52

**Comment by ashie** [comment]
Updated to fluent-plugin-opensearch 1.0.7
