### ISSUE TITLE
fluent-plugin-elasticsearch config should not specify user and password when they are empty

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd-kubernetes-daemonset#137]
fluent-plugin-elasticsearch does not assume empty user and password in configuration.
Where we should handle this issue?
Should we provide no-authenticate configuration?

[Here](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/templates/conf/fluent.conf.erb#L23-L24) is always specifying basic authentication information.

**Comment by repeatedly** [comment]
Hmm... this is hard problem.
We want to omit user/passward setting when environment variables are not set.
But I'm not sure k8s/container provides such feature or not.
