### ISSUE TITLE
Compatibility with Elasticsearch 8.x?

### ISSUE THREAD

**Issue by gregwhorley** [fluent/fluentd-kubernetes-daemonset#1373]
I'm currently on ES/Kibana 7.17.5 along with Fluentd running from the `v1.14-debian-elasticsearch7-1` image tag. Is this compatible with ES 8?

**Comment by ragsanil** [comment]
is it compatible? I am not able to connect to elasticsearch 8.1 with ssl

**Comment by gregwhorley** [comment]
I have `v1.15-debian-elasticsearch7-1` of this daemonset with `5.1.1` of the elasticsearch plugin bundled and have no problem connecting to 8.0.1 and 8.4.2 ES clusters over TLS.

> is it compatible? I am not able to connect to elasticsearch 8.1 with ssl
