### ISSUE TITLE
Typo in environment name: FLUENT_FOWARD_HOST

### ISSUE THREAD

**Issue by bwinter** [fluent/fluentd-kubernetes-daemonset#1383]
I think it should be FO**R**WARD.

Here: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.15/debian-forward/conf/fluent.conf#L15-L16

and

Here: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-forward.yaml#L29-L32

**Comment by cosmo0920** [comment]
Can we handle this issue, @ashie?
