### ISSUE TITLE
no such file or directory @rb_sysopen while deploying 'fluentd-daemonset-opensearch.yaml'

### ISSUE THREAD

**Issue by srinvasgutta** [fluent/fluentd-kubernetes-daemonset#1405]
Hi,

We are using AWS opensearch. Configuring Fluentd in AWS kubernetes cluster by deploying as daemonset using fluentd-daemonset-opensearch.yaml

Getting below error in pod logs. Please help on it to fix. I couldn't find any help in google regarding fix for this which is connecting to opensearch

====
[warn]: #0 [out_os] Could not communicate to OpenSearch, resetting connection and trying again. No such file or directory @ rb_sysopen -  (Errno::ENOENT)

====

Yaml file
=====

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: [node-role.kubernetes.io/control-plane](http://node-role.kubernetes.io/control-plane)
        effect: NoSchedule
      - key: [node-role.kubernetes.io/master](http://node-role.kubernetes.io/master)
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.15.3-debian-opensearch-amd64-1.0
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name:  FLUENT_OPENSEARCH_HOST
            value: "****************"
          - name:  FLUENT_OPENSEARCH_PORT
            value: "443"
          - name: FLUENT_OPENSEARCH_SCHEME
            value: "https"
          - name: FLUENT_UID
            value: "0"
          # Option to configure OpenSearch plugin with self signed certs
          # ================================================================
          - name: FLUENT_OPENSEARCH_SSL_VERIFY
            value: "true"
          # Option to configure OpenSearch plugin with tls
          # ================================================================
          # Authentication
          # =====================
          - name: FLUENT_OPENSEARCH_USER
            value: "**********"
          - name: FLUENT_OPENSEARCH_PASSWORD
            value: "**********"
          # Certificate
          # =====================
          # Fluentd Parser
          # =====================
          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            value: "cri"
          - name: FLUENT_CONTAINER_TAIL_PARSER_TIME_FORMAT
            value: "%Y-%m-%dT%H:%M:%S.%N%:z"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
        # - name: dockercontainerlogdirectory
        #   mountPath: /var/lib/docker/containers
        #   readOnly: true
        # When actual pod logs in /var/log/pods, the following lines should be used.
        - name: dockercontainerlogdirectory
          mountPath: /var/log/pods
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
      # - name: dockercontainerlogdirectory
      #   hostPath:
      #     path: /var/lib/docker/containers
      # When actual pod logs in /var/log/pods, the following lines should be used.
      - name: dockercontainerlogdirectory
        hostPath:
          path: /var/log/pods

**Comment by viktorgoranov** [comment]
Hello Team,

Any updates here? I am facing the same issue....
