### ISSUE TITLE
Loki output plugin addition

### ISSUE THREAD

**Issue by jgornowich** [fluent/fluentd-kubernetes-daemonset#1452]
I wanted to know if it was possible to add the [Loki Output Plugin](https://github.com/grafana/loki/tree/main/clients/cmd/fluentd) into the [debian-elasticsearch7](https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.16/debian-elasticsearch7) image that is maintained here.  

I can certainly make the contribution for it because I saw the reference that you aren't accepting new destination request without contribution. [#293](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/293)  Is this just a matter of adding the following to the https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.16/debian-elasticsearch7/Gemfile?

```
gem "fluent-plugin-grafana-loki", "~> 1.2.20"
```

I'm interested in getting it put in this maintained image because I am actually looking to work with https://repo1.dso.mil/dsop/opensource/fluentd/fluentd-kubernetes-daemonset image as my upstream.

If this is not something that can be added to the officially maintained image here, what is the best way to support adding this plugin separately?

**Comment by y0hnn** [comment]
Hey, also interested to add Loki support, but I have the same questions as @jgornowich
