### ISSUE TITLE
Image of v1.16.2-debian-s3-amd64-1.0 version

### ISSUE THREAD

**Issue by rodrigodealer** [fluent/fluentd-kubernetes-daemonset#1455]
Hi all,

I noticed that the version v1.16.2 is not present in Dockerhub on the s3 type, but it's present for the other types. 

How could we fix it?

**Comment by kenhys** [comment]
It seems that some of images are not published anymore.

ref. https://github.com/fluent/fluentd-kubernetes-daemonset#debian

you need to build it yourself.

**Comment by ashie** [comment]
> It seems that some of images are not published anymore.

It's not intentional, we should publish s3 image.

https://github.com/fluent/fluentd-kubernetes-daemonset/pull/1456#issuecomment-1718513976

**Comment by kenhys** [comment]
There were long standing limitation to publish s3 image for a long time after 1.16.1-debian-s3-amd64.
Now the issue was solved and successor version has been published, please use v1.16.5 or v1.17.0 image.
