### ISSUE TITLE
High CVEs in fluent/fluentd-kubernetes-daemonset:v1.16.2-debian-forward-1.0 image

### ISSUE THREAD

**Issue by AYUSHI-ERIC** [fluent/fluentd-kubernetes-daemonset#1467]
Hello High CVEs in image fluent/fluentd-kubernetes-daemonset:v1.16.2-debian-forward-1.0. Can anyone let know solution to the Critical and High risk (Security, License,Operational Risk)

**Comment by kenhys** [comment]
Please use the newer fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-forward-1.0 image.
