### ISSUE TITLE
Missing fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-s3-amd64-1.0 in Docker Hub

### ISSUE THREAD

**Issue by tunguyen9889** [fluent/fluentd-kubernetes-daemonset#1468]
The image `fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-s3-amd64-1.0` is missing in Docker Hub https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset, please help build and upload it.

**Comment by kenhys** [comment]
related with #1455

**Comment by ashie** [comment]
If I remember right, I published it manually in the previous release (v1.16.2).
It's not documented yet in MAINTINING.md because it's not ideal procedure.
We should replace Docker Hub's build automation with GitHub Actions.

**Comment by babinos87** [comment]
Same here, I could not find this image, but I can pull `1.16.2`
