### ISSUE TITLE
42 CVEs(including Critical and High) found in latest Docker image "fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-opensearch-1.0"

### ISSUE THREAD

**Issue by ira-gordin-sap** [fluent/fluentd-kubernetes-daemonset#1470]
[fluent_fluentd-kubernetes-daemonset_sha256_05982e549d22ff0d18460f46dd50787a378107ccb4b0a94d1f2aa8b76c33c242-alerts-report.xlsx](https://github.com/fluent/fluentd-kubernetes-daemonset/files/13889469/fluent_fluentd-kubernetes-daemonset_sha256_05982e549d22ff0d18460f46dd50787a378107ccb4b0a94d1f2aa8b76c33c242-alerts-report.xlsx)

**Comment by kenhys** [comment]
Thank you feedback.

But it seems that these are false-positive cases.

```
docker run --rm anchore/grype:latest fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-opensearch-1.0 | grep -v Negligible | grep -v "won't fix"
```

With excluding "Negligible" and "Won't fix" ones, only linux-libc-dev (header files) is detected.
NOTE: uri 0.12.1 is installed but not used because newer 0.12.2 is installed to fix CVE.

**Comment by ira-gordin-sap** [comment]
ok, so what with linux-libc-dev?

**Comment by kenhys** [comment]
It must be removed from not only base images, but also daemonset images itself.

https://github.com/fluent/fluentd-kubernetes-daemonset/pull/1476
Above PR will resolve it.

**Comment by kenhys** [comment]
```
docker run --rm anchore/grype:latest fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-opensearch-amd64-2.1 | grep -v Negligible | grep -v "won't fix"
NAME                INSTALLED          FIXED-IN     TYPE  VULNERABILITY        SEVERITY   
uri                 0.12.1             0.12.2       gem   GHSA-hww2-5g85-429m  Medium      
```

Above one is already known - false positive.
