### ISSUE TITLE
Kubernetes attribute is missing in cloudwatch logs when fluentd read application logs from files system different from  /var/log/containers/

### ISSUE THREAD

**Issue by chanthakim20** [fluent/fluentd-kubernetes-daemonset#1489]
### Describe the bug

My application logs was written to file system and then in Fluentd configMap, we changed the source file location to a different directory from /var/log/containers;

Fluentd reads from files system for example /var/mylogs/*.log and writes logs to CloudWatch without adding kubernetes attribute

Currently I am using Fluentd to cloudwatch plugin: v1.16.2-debian-cloudwatch-1.0.

Please advise if there is a way to have kubernetes attribute by updating Fluentd configuration.
 
This is an example when the application write logs to standard output inside /var/log/containers/*.log;
but when Fluentd read the logs from /var/mylogs/*.log, it doesn't include kubernetes attribute.

_No response_

**Comment by kenhys** [comment]
It seems that https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter is the plugin what you want to apply.
