### ISSUE TITLE
fluent/fluentd-kubernetes-daemonset:stable-logentries fails to start on k8s 1.10.x

### ISSUE THREAD

**Issue by mvernimmen** [fluent/fluentd-kubernetes-daemonset#157]
We have fluent/fluentd-kubernetes-daemonset:stable-logentries running on an k8s cluster version 1.8.5, fluentd works fine there. Recently we set up a new cluster with 1.10.4 on which we can't get fluentd to start. fluent/fluentd-kubernetes-daemonset:stable-logentries & fluent/fluentd-kubernetes-daemonset:v1.2-debian-logentries both fail to start.
kubectl describe shows:
```
Events:
  Type     Reason                 Age                From                     Message
  ----     ------                 ----               ----                     -------
  Normal   SuccessfulMountVolume  1m                 kubelet, kube-02.t.nl02  MountVolume.SetUp succeeded for volume "varlibdockercontainers"
  Normal   SuccessfulMountVolume  1m                 kubelet, kube-02.t.nl02  MountVolume.SetUp succeeded for volume "varlog"
  Normal   SuccessfulMountVolume  1m                 kubelet, kube-02.t.nl02  MountVolume.SetUp succeeded for volume "default-token-j8z7w"
  Normal   SuccessfulMountVolume  53s                kubelet, kube-02.t.nl02  MountVolume.SetUp succeeded for volume "kubernetesconf-config-volume"
  Normal   Pulling                43s (x2 over 52s)  kubelet, kube-02.t.nl02  pulling image "fluent/fluentd-kubernetes-daemonset:v1.2-debian-logentries"
  Normal   Pulled                 41s (x2 over 51s)  kubelet, kube-02.t.nl02  Successfully pulled image "fluent/fluentd-kubernetes-daemonset:v1.2-debian-logentries"
  Normal   Created                41s (x2 over 51s)  kubelet, kube-02.t.nl02  Created container
  Normal   Started                41s (x2 over 51s)  kubelet, kube-02.t.nl02  Started container
  Warning  FailedMount            40s                kubelet, kube-02.t.nl02  MountVolume.SetUp failed for volume "kubernetesconf-config-volume" : remove /var/lib/kubelet/pods/633c7fa2-7bab-11e8-b599-525400a39777/volumes/kubernetes.io~configmap/kubernetesconf-config-volume/..2018_06_29_14_48_18.229754963/kubernetes.conf: device or resource busy
```
I upgraded the new cluster to 1.10.5 but it made no difference.
Is the fluentd container not compatible with kubernetes 1.10.x ?

**Comment by jwitrick** [comment]
I recently had the same issue, I tried to setup fluent on Amazon EKS and it kept failing immediately. I was able to solve this by adding an environment variable to the fluentd-ds.yaml file:
env:
  - name: AWS_REGION
    value: <region_where_my_cluster_lives>

Not sure if this is the same issue you are facing or not, but once I added it the fluent containers started running in my k8s cluster.

**Comment by repeatedly** [comment]
I didn't follow k8s 1.10 changes.
Does anyone have an idea for this issue?

**Comment by mvernimmen** [comment]
I'm running on-premise, so I doubt setting AWS_REGION will make any difference.

The problem seems to be caused by my deployment trying to override/replace `/fluentd/etc/kubernetes.conf`. When I mount my configmap as `/fluentd/etc/kubernetes.conf2` it starts fine but then I'm not able to use my own configuration for fluentd (because kubernetes.conf2 is not loaded, fluentd.conf only imports kubernetes.conf and systemd.conf). Perhaps something changed in the way we're supposed to configure fluentd and I simply didn't notice?

**Comment by mvernimmen** [comment]
I couldn't reproduce the problem with minikube and version 1.10.5
I will create a new cluster using kubespray and then see whether it'll work fine there. Perhaps it's a problem in my existing cluster.

**Comment by mvernimmen** [comment]
The new kubespray cluster has the same problem.
