### ISSUE TITLE
Don't sed elasticsearch on non-elasticsearch images 

### ISSUE THREAD

**Issue by jamielennox** [fluent/fluentd-kubernetes-daemonset#161]
The entrypoint script has a holdover of doing 

```
if [ -z ${FLUENT_ELASTICSEARCH_USER} ] ; then
   sed -i  '/FLUENT_ELASTICSEARCH_USER/d' /fluentd/etc/${FLUENTD_CONF}
fi

if [ -z ${FLUENT_ELASTICSEARCH_PASSWORD} ] ; then
   sed -i  '/FLUENT_ELASTICSEARCH_PASSWORD/d' /fluentd/etc/${FLUENTD_CONF}
fi
```

I'm assuming it's for some legacy thing. Anyway, the way I use this image is I mount a custom configMap on /fluentd/etc/ and deal with my own config there. 

I'm not using elastic search so i don't have those env variables set and so it tries to sed my fluentd.conf but sed fails because the destination is not writable. 

Can we remove these statements? Why would we support a find and replace in fluent config, it can't be made to use #{ENV['X']}? They don't actually replace a real value just delete old ones. 

If not can we at least isolate them to only be relevant to the elasticsearch image? 

Workaround, if i set those env vars to any value it skips the sed and continues to work.

**Comment by repeatedly** [comment]
Removed by https://github.com/fluent/fluentd-kubernetes-daemonset/pull/163
