### ISSUE TITLE
debian builds failing in docker pipeline

### ISSUE THREAD

**Issue by therealgambo** [fluent/fluentd-kubernetes-daemonset#162]
After PR #148 was accepted looks like all debian v1.2 based images are failing to build within the docker pipeline.

- https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/builds/

Error message: `standard_init_linux.go:190: exec user process caused "exec format error"`

Any ideas? I have built all images affected by the PR on my local machine without any issues.

**Comment by repeatedly** [comment]
I found the problem is fluentd-docker-image side.
I'm now fixing the images.

**Comment by repeatedly** [comment]
Fixed: https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/builds/
