### ISSUE TITLE
'filters' parameter is deprecated

### ISSUE THREAD

**Issue by stefanax** [fluent/fluentd-kubernetes-daemonset#167]
Using v1.2-debian-cloudwatch (although I guess this might affect all v1.2 images) I get this log row three times:

`2018-07-04 06:30:16 +0000 [warn]: 'filters' parameter is deprecated: filters has been renamed as matches`

I did a quick test to downgrade to v1.1 and I didn't get this error, and to my understanding v1.2 has a later version of Ruby than v1.1. Therefor I suspect this is an issue of a new Ruby version. But as I've never touched Ruby and I lack time so I haven't been able to put some work into this to test my theory, or find a fix.

**Comment by akefirad** [comment]
Hi there. I'm seeing the warning too. What's the status of this ticket? Thanks.
