### ISSUE TITLE
v0.12.33-cloudwatch standard_init_linux.go:187 error

### ISSUE THREAD

**Issue by VincentCouzij** [fluent/fluentd-kubernetes-daemonset#170]
The fluent/fluentd-kubernetes-daemonset:v0.12.33-cloudwatch images was rebuilt 6 days ago (why?) and now I'm getting the following error `standard_init_linux.go:187: exec user process caused "no such file or directory"` in each container when running the daemon set.

**Comment by williamsandrew** [comment]
Same here. All of our logging containers blew up over the weekend. Upgrading to tag `v1.2-debian-cloudwatch` seems to have resolved the issue for us.

**Comment by repeatedly** [comment]
Does v0.12.43 also have same problem?
We fixed this problem by this patch: https://github.com/fluent/fluentd-kubernetes-daemonset/pull/165

**Comment by VincentCouzij** [comment]
v0.12.43 did not work out of the box but with @thereverendtom his solution in https://github.com/fluent/fluentd-kubernetes-daemonset/issues/168

I added this to the daemonset.yaml 
`
- name: FLUENT_UID
   value: "0"
`

Please don't update images that are already built. `v0.12.33-cloudwatch` should've never been changed. Anyway thank you for making these images.

**Comment by mbolek** [comment]
Yup, got bitten by the issue as well. Odd idea to rebuild all the images which caused some failures though. What was the reason behind this?
Also, moving to v0.12.32-elasticsearch fixed that issue but as reported by VincentCouzij, this created another issue with fluentd no longer running as root user - this seems like a big change
