### ISSUE TITLE
GCS images are not available on Dockerhub

### ISSUE THREAD

**Issue by asdfgasfhsn** [fluent/fluentd-kubernetes-daemonset#175]
I am unable to pull any of the GCS image tags from Dockerhub. When trying to pull any of the 3 images I get the following;

    $ docker pull fluent/fluentd-kubernetes-daemonset:v0.12-debian-gcs
    Error response from daemon: pull access denied for fluentd-kubernetes-daemonset, repository does not exist or may require 'docker login'

I am able to pull other tags successfully.

**Comment by Jeyanthinath** [comment]
me too got into this issue, any update on this issue ? 
```
jaes-MacBook-Pro:k8s jaeraam$ docker pull fluent/fluentd-kubernetes-daemonset:gcsError response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:gcs not found
```

**Comment by repeatedly** [comment]
We just built gcs images. Test it: https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/tags/

**Comment by okkez** [comment]
I could not find out the docker image tagged as gcs.

```
$ docker pull fluent/fluentd-kubernetes-daemonset:gcs
Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:gcs not found
```

**Comment by cosmo0920** [comment]
Currently, we just build gcs images the following tags:
* v1.11-debian-gcs-1 (For x86_64)
* v1.11-debian-gcs-arm64-1 (For aarch64)

In more detail, please refer to README:

* https://github.com/fluent/fluentd-kubernetes-daemonset#x86_64-images
* https://github.com/fluent/fluentd-kubernetes-daemonset#arm64-images
