### ISSUE TITLE
Providing aws credentials in the fluentd conf file

### ISSUE THREAD

**Issue by lp060** [fluent/fluentd-kubernetes-daemonset#182]
Hi,

I am using fluentd-kubernetes-daemonset for redirecting logs to kinesis. I see that the conf file does not have provision to specify the aws credentials. It assumes that the IAM profile exists. Actually, I have the setup with minikube in my  local machine and I dont have any IAM role. I have created a test kinesis stream in AWS where I would like my logs to go. I have specified the kinesis stream name as env variable but I dont have option to specify the credentials. Hence would like to specify the aws credentials in the conf file. Is there anyway I can do that?

**Comment by lp060** [comment]
Hi,

Any help on this please?

**Comment by shiftky** [comment]
aws-fluent-plugin-kinesis plugin automatically fetches credential from environment variables.
https://github.com/awslabs/aws-fluent-plugin-kinesis#configuration-credentials

You can store AWS access keys as Secret and use in environment variables with name `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in the DaemonSet configuration file.
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by cosmo0920** [comment]
Solution is answered in https://github.com/fluent/fluentd-kubernetes-daemonset/issues/182#issuecomment-452285942.
Closing.
