### ISSUE TITLE
fluentd not forwarding logs onto cloudwatch log group

### ISSUE THREAD

**Issue by rdr411** [fluent/fluentd-kubernetes-daemonset#183]
I have created a fluentd-kubernetes-daemonset with our existing kubernetes cluster. When I ssh onto the fluentd nodes within the K8 cluster I can see logs under /var/log/containers. However, fluentd is not parsing logs onto the Cloudwatch log group.

**Comment by sputnik13** [comment]
Have you checked fluentd pod logs?  I had similar issues where the problem turned out to be fluentd kept getting restarted by OOM killer in kubernetes, increasing memory limit in the daemonset definition resolved this.

**Comment by stijndehaes** [comment]
@rdr411 did you ever found out the problem?

**Comment by michalrabinowitch** [comment]
@rdr411 curious to how you resolved this?
