### ISSUE TITLE
Daemonset to SQS

### ISSUE THREAD

**Issue by mmailhos** [fluent/fluentd-kubernetes-daemonset#187]
Hi all, 

Would anyone have a fluentd-kubernetes-daemonset to SQS Output example?

Otherwise, I'm willing to contribute, based on https://github.com/ixixi/fluent-plugin-sqs, for example.

**Comment by repeatedly** [comment]
Pending the merge because we're not sure SQS destination is popular or not in k8s use-case.

**Comment by kenhys** [comment]
As of deployment process was improved, there is a room for newer image build pipeline if user helps **continuously maintain**  the image.  if you still have interest to do it, please create PR.
