### ISSUE TITLE
Fluentd Kubernetes splunk

### ISSUE THREAD

**Issue by cricketfan5** [fluent/fluentd-kubernetes-daemonset#191]
We are using fluentd as a daemonset on kubernetes to forward logs to Splunk. It was able to forward 95% of logs to Splunk and missing the 5%. I don't see any fluentd logs or any related info in the logs when and why it is failing to transfer the other 5% logs. Any help is appreciated. Thanks !!

**Comment by repeatedly** [comment]
> why it is failing to transfer the other 5% logs

You can use other output destination, e.g. S3, to check which point has the problem.
If the result is same, input or filter has a problem.
If the result is different, splunk or splunk plugin has a problem.
