### ISSUE TITLE
Fluentd Kubernetes Not Caching AWS Elasticsearch DNS Entry

### ISSUE THREAD

**Issue by ghost** [fluent/fluentd-kubernetes-daemonset#195]
Not sure if this is a problem with fluentd itself or kubernetes, but the pods running fluentd are not caching the dns entries for the AWS elasticsearch. For every call it makes (which we all know it is a lot) it has to do a lookup to get the ES endpoint. Is there anyway to set that up in fluentd? I have seen this config "expire_dns_cache" but that only works with the forward plugin, and not the elasticsearch one 
https://docs.fluentd.org/v0.12/articles/out_forward#expire_dns_cache

**Comment by repeatedly** [comment]
@cosmo0920 AFAIK, elasticsearch plugin caches client itself. Does elasticsearch-ruby look-up DNS at every insertion?

**Comment by cosmo0920** [comment]
elasticsearch-ruby does not handle keep-alive by default.
Also, elasticsearch plugin uses default elasticsearch-ruby client behavior by default.
If you want to reduce DNS look-up, you can use typhoeus http backend which have been introduced since v2.11.4.
To use this, install typhoeus gem and `http_backend typhoeus`.

**Comment by dlbarduzzi** [comment]
@cosmo0920 what plugin are you talking about for version v2.11.4? Is it the 'fluent-plugin-elasticsearch'? And any reason why typhoeus is not used as default, since we make a lot of calls to elasticsearch?

**Comment by dlbarduzzi** [comment]
Just to add more info, currently I have fluentd deployed in a kubernetes cluster (the cluster has more than 100 nodes running). The image I'm using is the "v0.12-debian-elasticsearch". And I'm sending the logs to an AWS Elasticsearch cluster. I'm not using any type of authentication to the ES, so no reason to use the aws-elasticsearch-service plugin as of now. I'm using the elasticsearch output plugin. Since there are a lot of nodes on the kubernetes cluster, it sends a lot of messages to the ES as expected. And for every message, it does a dns lookup for the ES endpoint. How can I improve this? Any suggestions are very appreciated.

**Comment by cosmo0920** [comment]
Yes, I'm talking about fluent-plugin-elasticsearch.
fluent-plugin-elasticsearch v1.x does not provide keep-alive connection feature which is provided by another HTTP backend such as typhpeus....

**Comment by cosmo0920** [comment]
And I have no plan to backport typhoeus backend patch from v2.x series.

**Comment by dlbarduzzi** [comment]
even when I use fluentd 1.2 version and install typhoeus I still get an error from the configs. The logs below are from the kubernetes pod, which it clearly says "Successfully installed typhoeus-1.3.0", and after that the config error is thrown.

Successfully installed ethon-0.11.0
Successfully installed typhoeus-1.3.0
2 gems installed
2018-09-17 19:41:11 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/conf/fluent.conf"
2018-09-17 19:41:11 +0000 [warn]: 'log_level' is deprecated parameter name. use '@log_level' instead.
2018-09-17 19:41:12 +0000 [error]: config error file="/fluentd/etc/conf/fluent.conf" error_class=Fluent::ConfigError error="You must install typhoeus gem."

**Comment by dlbarduzzi** [comment]
@repeatedly @cosmo0920 any idea on what could be happening? Really appreciate the help.

**Comment by chapitos** [comment]
One should install curl. More precisely, typhoeus needs libcurl to be installed in order to work. The real exception is masked by "You must install typhoeus gem" message. The image we have used in our tests is fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.2.

**Comment by HarishHothi** [comment]
Hi @chapitos and @cosmo0920  , I tried using `fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.2` with 

> gem install fluent-plugin-elasticsearch -v 3.2.2 \
>  gem install curl -v 0.0.9 \
> gem install typhoeus 

But still getting same error

`time="2019-02-19T06:53:11Z" level=debug msg="Checked config for namespace demo1 with fluentd and got: 2019-02-19 06:53:11 +0000 [error]: config error file=\"/tmp/validate-ext-demo1933070428\" error_class=Fluent::ConfigError error=\"You must install typhoeus gem.\""
time="2019-02-19T06:53:11Z" level=info msg="Configuration for namespace demo1 cannot be validated with fluentd"
time="2019-02-19T06:53:11Z" level=debug msg="Saving status: &Namespace{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:demo1,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{logging.csp.vmware.com/fluentd-status: 2019-02-19 06:53:11 +0000 [error]: config error file=\"/tmp/validate-ext-demo1933070428\" error_class=Fluent::ConfigError error=\"You must install typhoeus gem.\",},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:NamespaceSpec{Finalizers:[],},Status:NamespaceStatus{Phase:,},}, <nil>"
`

**Comment by repeatedly** [comment]
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.3/debian-elasticsearch/entrypoint.sh#L16

This image uses Gemfile based gem management to avoid version mismatch.
Add gem to Gemfile instead.

https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.3/debian-elasticsearch/Gemfile

**Comment by chapitos** [comment]
@HarishHothi ,
I have not installed curl as a Ruby gem but as Debian package (apt install...). The exact steps I used during debuggin are described below. Please note that doing "apt update" in a daemonset startup script is not a best thing to do (longer container startup, uncleaned resources, etc). It is better to bake your docker image (and perform all needed installations as part of docker image baking), or wait for a fix from fluentd:
Steps I used to get it running during debugging are as follows:
* Start fleuntd using the Docker image mentioned above
* The containers part of k8s daemonset descriptor I used is shown below. Please note that curl is installed as a Debian package. Important commands here are apt update, apt install and gem install. Other are irrelevant to this particular issue.
```containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.2
        command: [ "/bin/sh" ]
        args: [ "-c", "mkdir -p /fluentd/config ; apt update -y ; apt install curl -y ; gem install typhoeus -v 1.3.1 ; sh /fluentd/entrypoint.sh"]
```
* Finally you need to switch typheous on in the configuration by setting:
`http_backend typhoeus `
in your fluent.conf
Again, the solution above was used only for debugging purposes. You should not execute apt update as above and not cleaning up unneeded resources after update.

**Comment by HarishHothi** [comment]
@repeatedly and @chapitos  Thank you for the suggestion. It worked after i installed curl via apt-get.

**Comment by cosmo0920** [comment]
Using typhoeus is one of the solutions.
And original reporter is gone from GitHub. We cannot handle this issue anymore. Closing.
