### ISSUE TITLE
RabbitMQ plugin

### ISSUE THREAD

**Issue by maxpain** [fluent/fluentd-kubernetes-daemonset#204]
Hi. Please add RabbitMQ / AMQP support.

**Comment by MathieuMailhos** [comment]
Pull Request #248

**Comment by jojotheboss** [comment]
I really need that PR. Please merge :-)

**Comment by kenhys** [comment]
As of deployment process was improved, there is a room for newer image build pipeline if user helps **continuously maintain**  the image.  if you still have interest to do it, please create PR.
