### ISSUE TITLE
possibility to add/install 'fluent-plugin-grok-parser' plugin in the elasticsearch version

### ISSUE THREAD

**Issue by hkailantzis** [fluent/fluentd-kubernetes-daemonset#214]
Is there any possibility to add/install 'fluent-plugin-grok-parser' plugin in the elasticsearch version ?

**Comment by mleneveut** [comment]
Did you find a solution ? I'd like to add it too in fluent/fluentd-kubernetes-daemonset:elasticsearch

**Comment by MichaelKunze** [comment]
Looks like the only way is to fork this repo and change the appropriate Gemfile and build it yourself.

**Comment by repeatedly** [comment]
Another way is sending a patch :)
