### ISSUE TITLE
Custom configs

### ISSUE THREAD

**Issue by bcottinghamae** [fluent/fluentd-kubernetes-daemonset#216]
How can I add a custom config to my daemonset deployment,  to e.g., do multiline parsing?

**Comment by okkez** [comment]
You can overwrite config files using [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/).

**Comment by EldarSagirov** [comment]
> You can overwrite config files using [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/).

Hi, can i ask you how i can add new "include" sections in main(fluent.conf) config?

**Comment by msacchiPPRO** [comment]
> You can overwrite config files using [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/).

Since K8s 1.9.x configmaps are mounted readonly, and fluentd fails to start with:

```
sed: couldn't open temporary file /fluentd/etc/sedt0TeWE: Read-only file system
```

I am mounting a whole config map to /fluentd/etc.

**Comment by paoll** [comment]
@msacchiPPRO It's right here https://github.com/fluent/fluentd-kubernetes-daemonset#disable-sed-execution-on-elasticsearch-image
