### ISSUE TITLE
sub-second time precision missing for elasticsearch output

### ISSUE THREAD

**Issue by secat** [fluent/fluentd-kubernetes-daemonset#22]
Currently the sub-second time precision is missing when sending logs to ElasticSearch.

This ends up with logs of with following time format (i.e. `000` for the sub-second precision):
```
May 25th 2017, 08:10:51.000	
```
The [fluent-plugin-elasticsearch 1.9.5](https://github.com/uken/fluent-plugin-elasticsearch/releases/tag/v1.9.5) plugin provides a new [time_precision](https://github.com/uken/fluent-plugin-elasticsearch#time_key) configuration parameter.

This new configuration parameter value should be set to:
```
time_precision 3
```

**Comment by edsiper** [comment]
looking at the code my understanding is that if no time_key is given (which is not our case) the plugin will generate it own timestamp including sub-second precision:

https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L294

this behavior would override the real record timestamps that we are gathering.

Note that Fluentd 0.14 and Fluent Bit 0.12 both comes with native sub-second support. Both versions should be available in a few weeks for production usage.

**Comment by edsiper** [comment]
Closing this issue for now.
