### ISSUE TITLE
How audit logs collection works?

### ISSUE THREAD

**Issue by omerlh** [fluent/fluentd-kubernetes-daemonset#223]
Audit logs exist only on master nodes, so to collect them fluentd has to run also on master nodes. I couldn't find anything on the daemonset that makes fluentd to do so - what am I missing?

**Comment by repeatedly** [comment]
Need `NoSchedule` setting in master tolerations?

**Comment by omerlh** [comment]
Doesn't that mean that fluentd will not be running on masters?
