### ISSUE TITLE
Question: send to 2 different destinations (ex: graylog and kafka)

### ISSUE THREAD

**Issue by rpelissi** [fluent/fluentd-kubernetes-daemonset#225]
Hi,
I am very interested by fluentd in kubernetes but I would like to know if there is a way to have 2 different outputs, like graylog and kafka? I know that some conf allow to send to one of the other but I am wondering if we can set 2 destinations for the daemonset?

Thanks!

**Comment by rpelissi** [comment]
Thanks for the comment :)

**Comment by couldntcatchthebus** [comment]
is there any example for that?
