### ISSUE TITLE
kubernetes field is shown as unkown in kibana

### ISSUE THREAD

**Issue by Mymetique** [fluent/fluentd-kubernetes-daemonset#229]
Hello,

I've installed the fluentd kubernetes deamonset and it is working properly, ie : it is sending logs to our elastic search. But when we try to explore our logs with kibana, the kubernetes field is written as ? with type unkown, making it impossible to query. On the other hand some nested fields of the kubernetes object are shown as searchable with the right type but since the root object kubernetes is unknown we can't do anything with them. Is there any kind of extra conf or file we should look into ?

Thank you very much.

**Comment by repeatedly** [comment]
Is this Elasticsearch or kibana question?
If so, this is not right place.
