### ISSUE TITLE
apache solr support

### ISSUE THREAD

**Issue by mjhea0** [fluent/fluentd-kubernetes-daemonset#250]
I'm working on a daemonset for connecting to Apache Solr via https://github.com/mosuka/fluent-plugin-output-solr. if I get this working, do you want me to add it to this repo?

**Comment by repeatedly** [comment]
> do you want me to add it to this repo?

Currently, we don't add new maintainer for each destination.
For images, if some users want solr destination on the production, we can add it to our images like https://github.com/fluent/fluentd-kubernetes-daemonset/pull/179

**Comment by ESA-Security-Group** [comment]
#247

**Comment by kenhys** [comment]
As of deployment process was improved, there is a room for newer image build pipeline if user helps **continuously maintain**  the image even though still have #293 issue. if you still have interest to do it, please create PR.
