### ISSUE TITLE
S3 output on daemonset overwriting each other?

### ISSUE THREAD

**Issue by davidchua** [fluent/fluentd-kubernetes-daemonset#251]
I noticed that in 

https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.3/debian-s3/conf/fluent.conf#L17 

there doesn't appear to be a node identifier in the `s3_object_key_format`. Wouldn't this create a situation where each daemonset pod has the same `index` and hence overwrite each other or have I misunderstood `index` wrongly?

**Comment by repeatedly** [comment]
Hmm... yeah. It is possible when flush timing is same between fluentd instance.
To avoid it, adding pod specific data to path.
In addition, provide FLUENT_S3_xx like environment variable to specify s3-object_key_format.

**Comment by fvasco** [comment]
Do you plan to fix this race issue in the main repository?

**Comment by repeatedly** [comment]
Patch for specifying customized s3_object_key_format: https://github.com/fluent/fluentd-kubernetes-daemonset/pull/507
Using `%{uuid_flush}` and other placeholder may fix this problem.

**Comment by fvasco** [comment]
Thank you @repeatedly to address this issue.
For our use case, we need to rebuild the logs in sequence, so we use the Kubernetes node IP to keep the same identifier across Pod's reboot.

However provides a fully customizable way to define file pattern is the way to go, I agree.
I suggest you to warn Kubernetes's users about this **possible** issue and to explain them how to configure fluentd correctly.

**Comment by fvasco** [comment]
Hi @repeatedly

> Using %{uuid_flush} and other placeholder may fix this problem.

We tried the new version, we got the error:

~~~
[error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="uuidtools gem not found. Install uuidtools gem first"
~~~

Can you provide some other advice?

**Comment by repeatedly** [comment]
https://github.com/fluent/fluentd-kubernetes-daemonset/pull/509

We forgot to update fluent-plugin-s3. Newer image should work with `%{uuid_flush}`.

> I hope this work as well:

yes. `${chunk_id}` also should work.
