### ISSUE TITLE
$['kubernetes']['namespace_name'] : Custom ConfigMap not generating value

### ISSUE THREAD

**Issue by sharmmoh1983** [fluent/fluentd-kubernetes-daemonset#253]
I am trying to write custom config map for my fluentd daemonset for creating elastic search index based on kubernetes namespace.

```
 # we send the logs to Elasticsearch
    <match kubernetes.**>
        @type elasticsearch
        include_tag_key true
        host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
        port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
        scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
        ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
        reload_connections true
        logstash_prefix logstash-MYCLUSTERNAME-$['kubernetes']['namespace_name']
        logstash_format true
        <buffer>
            flush_thread_count 8
            flush_interval 5s
            chunk_limit_size 2M
            queue_limit_length 32
            retry_max_interval 30
            retry_forever true
        </buffer>
    </match>



```
Now when I see the index in ES , I get logstash-myclustername-$['kubernetes']['namespace_name']-2019.01.28

and not the equivalent values 

I have tried logstash-myclustername-${record['kubernetes']['namespace_name'] also but no use

Please let me know how to access these values in config map

**Comment by cosmo0920** [comment]
> I have tried logstash-myclustername-${record['kubernetes']['namespace_name'] also but no use
> 
> Please let me know how to access these values in config map

This is because your ES plugin's buffer metadata doesn't include `$['kubernetes']['namespace_name']` value:

```aconf
        <buffer tag, $['kubernetes']['namespace_name']>
            flush_thread_count 8
            flush_interval 5s
            chunk_limit_size 2M
            queue_limit_length 32
            retry_max_interval 30
            retry_forever true
        </buffer>
```

`$['kubernetes']['namespace_name']` should be needed in buffer directive attributes.
