### ISSUE TITLE
Only Send Log Message to Cloudwatch

### ISSUE THREAD

**Issue by aheimowitz** [fluent/fluentd-kubernetes-daemonset#259]
When using the fluentd-daemonset-cloudwatch-rbac is there a way to only send the log message to cloudwatch? The current message format im getting is a json object containing the log as well as all the kubernetes information which I really dont need and I feel as though its just clogging up the logs. Please see below for the format I am currently getting.

`{
    "log": "test\n",
    "stream": "stdout",
    "docker": {
        "container_id": "97f0f7f058d5892bb2a4e199454a1e6635925f258449e95d309cd0bd69bc0039"
    },
    "kubernetes": {
        "container_name": "test",
        "namespace_name": "test",
        "pod_name": "test-1217016741-8skpz",
        "container_image": "testImage",
        "container_image_id": "docker-pullable://testImage",
        "pod_id": "e8fb347d-1910-11e9-b568-1292df33fb88",
        "labels": {
            "app": "test",
            "pod-template-hash": "1217016741"
        },
        "host": "ip-1-1-1-1.ec2.internal",
        "master_url": "https://1.1.0.1:443/api",
        "namespace_id": "f3e876ca-6598-11e7-99c1-12089b091b1c"
    }
}`

**Comment by a6kme** [comment]
You can either remove the filter which contains `kubernetes_metadata`, or you can customise the filter to contain only relevant metadata. Below is what I am using, and it serves my purpose. `skip_` are documented in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter#configuration

```
<filter **>
    @type kubernetes_metadata
    @id filter_kube_metadata_application
    skip_labels true
    skip_container_metadata true
    skip_master_url true
    skip_namespace_metadata true
</filter>
```

Also, if you want specific key from kubernetes metadata, you can do the below

```
<filter **>
    @type record_transformer
    @id filter_normal_stream_transformer_application
    enable_ruby true
    <record>
        container_name ${record.dig("kubernetes", "container_name")}
    </record>
    remove_keys $.kubernetes, $.docker
</filter>
```

Hope it helps.
