### ISSUE TITLE
Rebuild 0.12 debian images due to security bugs

### ISSUE THREAD

**Issue by llarsson** [fluent/fluentd-kubernetes-daemonset#261]
Please rebuild all 0.12 debian images due to critical security bugs as identified by JFrog Xray. If you just build with `--pull` and `--no-cache`, it should be fine.

**Comment by repeatedly** [comment]
We use automated build on docker hub. Clicking trigger is enough?

**Comment by llarsson** [comment]
I assume so, if done in the right order, since there is a lot of "this image depends on this other image" going on. 🙂

On January 31, 2019 10:07:00 AM GMT+01:00, Masahiro Nakagawa <notifications@github.com> wrote:
>We use automated build on docker hub. Clicking trigger is enough?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fluent/fluentd-kubernetes-daemonset/issues/261#issuecomment-459269437

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
