### ISSUE TITLE
Able to set elasticsearch index name via env variable

### ISSUE THREAD

**Issue by osimmasgard** [fluent/fluentd-kubernetes-daemonset#263]
Hi,

I have been searching in vain for a way to customize which index you want fluentd to write to in es, this without overwriting the fluent.conf which some people have suggested.
Would it be possible to have a env variable like so:

FLUENT_ELASTICSEARCH_INDEX

Thanks

**Comment by osimmasgard** [comment]
I've added the changes and tried to make a pull request but I had no permission to upload my branch.
Please advice on how I should proceed. Thanks

```ruby
<match **>
   @type elasticsearch
   @id out_es
   @log_level info
   include_tag_key true
   host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
   port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
   path "#{ENV['FLUENT_ELASTICSEARCH_PATH']}"
   scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
   ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
   ssl_version "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERSION'] || 'TLSv1'}"
   user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
   password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
   reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'true'}"
   reconnect_on_error "#{ENV['FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR'] || 'false'}"
   logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'logstash'}"
   logstash_format "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT'] || 'true'}"
   index_name "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME'] || 'logstash'}"
   type_name "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_TYPE_NAME'] || 'fluentd'}"
<% if is_v1 %>
   <buffer>
     flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
     flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
     chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
     queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
     retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
     retry_forever true
   </buffer>
```

**Comment by repeatedly** [comment]
> I had no permission to upload my branch.

What does this mean?
You can't push your branch to your repository?
Or if you are not familiar with fork/pr, check github document first: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by osimmasgard** [comment]
You werer right, this is actually my first commit towards a repo I don't own or has edit rights to. But hopefully I did it correctly now after following the guide you linked to.

https://github.com/fluent/fluentd-kubernetes-daemonset/pull/264

**Comment by ishantanu** [comment]
Is this feature working? I am trying to set `index_name` for the logs in a simpler way with this daemonset deployment but could not find a way.  I tried setting an env var:
```
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
            value: "fluentd"
```

but this did not work either.
