### ISSUE TITLE
Is there a plan to add plugin fluent-plugin-multi-format-parser ?

### ISSUE THREAD

**Issue by qqbuby** [fluent/fluentd-kubernetes-daemonset#265]

**Comment by maximdx** [comment]
Not sure.
But you can load your own entrypoint.sh by config map to add the plugins you like.

**Comment by cosmo0920** [comment]
Already included: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/templates/Gemfile.erb#L11
Closing.
