### ISSUE TITLE
time resolution, is there a way to change it ?

### ISSUE THREAD

**Issue by zerthimon** [fluent/fluentd-kubernetes-daemonset#267]
The messages that appear in container log sometimes have different order in elasticsearch.
Is there a way to change time res to nanosec ?

**Comment by zerthimon** [comment]
hmm, in the source there is a block
```
  <parse>
    @type json
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </parse>```

Also I have this date in ES docs:
```
    "@timestamp": "2019-02-27T19:29:54.025305658+00:00",
    "tag": "kubernetes.var.log.containers.image-generator-f9f75c5b7-l7q5l_stage-image-generator_image-generator-46c7a67c95b50f845fc7c5b98762f55ac6541562193bfcf914bcfe4e5671d195.log"
  },
  "fields": {
    "@timestamp": [
      "2019-02-27T19:29:54.025Z"
    ]
  },
```
So this looks like I need to tell kibana to use the first @timestamp field somehow

**Comment by repeatedly** [comment]
AFAIK, ES doesn't support nanosecond timestampe yet.

**Comment by cosmo0920** [comment]
Elasticsearch 7 will include nanoseconds precision timestamp:
https://github.com/elastic/elasticsearch/pull/37755

It will be able to use [`date_nanos`](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/date_nanos.html) field type.
If you are interested in nano precison timestamp, could you use ES 7.x beta?
