### ISSUE TITLE
Install via Gemfile?

### ISSUE THREAD

**Issue by c-knowles** [fluent/fluentd-kubernetes-daemonset#27]
Is there any specific reason we wish to put the `gem install`s directly in the Dockerfile or could we [use a Gemfile](https://github.com/kubernetes/contrib/blob/master/fluentd/fluentd-gcp-image/Dockerfile#L38) for each permutation?

**Comment by edsiper** [comment]
no specific reason

**Comment by errm** [comment]
`Gemfile` + `Gemfile.lock` would make the build process deterministic, and give us vulnerability warnings in GitHub https://help.github.com/articles/viewing-and-updating-vulnerable-dependencies-in-your-repository/

I am happy to work on this, unless there are objections?
