### ISSUE TITLE
fluentd syslog output plugin to send logs to remote syslog server with TLS

### ISSUE THREAD

**Issue by ctyjrsy** [fluent/fluentd-kubernetes-daemonset#271]
I am new to fluentd and am able to collect logs from Kubernetes cluster, however I am hoping to send logs to a remote syslog server with ssl and cert file.

Is there a TLS supported output syslog implementation right now?

**Comment by aerostitch** [comment]
This project uses [fluent-plugin-kubernetes_remote_syslog](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.3/debian-syslog/Gemfile#L11) which, according to the code here https://github.com/georgegoh/fluent-plugin-kubernetes_remote_syslog/blob/master/lib/fluent/plugin/out_kubernetes_remote_syslog.rb doesn't implement the TLS flag from the underlying library it's using.

So I created https://github.com/georgegoh/fluent-plugin-kubernetes_remote_syslog/pull/5.
Once it's merged you should be able to use that to send logs using TLS with the syslog protocol.

**Comment by cosmo0920** [comment]
Currently, https://github.com/dlackty/fluent-plugin-remote_syslog is also supported TLS flag.
Does anyone wants to handle TLS connection for Syslog on k8s daemonsets?

**Comment by cosmo0920** [comment]
Ah! This repository is already supported TLS connection on syslog daemonset:
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.11/debian-syslog/conf/fluent.conf#L20-L21

Closing.
