### ISSUE TITLE
JSON parser not working

### ISSUE THREAD

**Issue by ChSch3000** [fluent/fluentd-kubernetes-daemonset#273]
I'm trying to parse following log as JSON (Note: sample ouput is from console, not from the docker container log files)

Environment:
Fluentd image: fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.3
Elasticsearch: v6.6 

```
{"level":"info","msg":"this is a test log - json","time":"2019-02-22T14:36:05Z"}
time="2019-02-22T14:36:05Z" level=info msg="this is a test log"
this is a test log
{"level":"info","msg":"this is a test log - json","time":"2019-02-22T14:36:15Z"}
time="2019-02-22T14:36:15Z" level=info msg="this is a test log"
this is a test log
this is a test log
{"level":"info","msg":"this is a test log - json","time":"2019-02-22T14:36:25Z"}
time="2019-02-22T14:36:25Z" level=info msg="this is a test log"
```

This is my custom parser config which is mounted as config map in the fluentd pod. This is working as expected as I see the filter in the fluentd config.
```
<filter kubernetes.**>
   @type parser
   <parse>
      @type json
      json_parser json
   </parse>
   replace_invalid_sequence true
   emit_invalid_record_to_error false
   key_name log
   reserve_data true
</filter>
```

But if I activate this filter, I can't see the JSON logs in Kibana anymore.
Here is the screenshot from Kibana. As you can see, the JSON log seems supressed / ignored. While the "normal" logs and Sysout log are displayed as usual.
![image](https://user-images.githubusercontent.com/6421265/53250731-45d6cc80-36bb-11e9-91f9-b18fbfc02517.png)

There are some similar Issues, but none of them help me.
#193 
#181

**Comment by repeatedly** [comment]
No error log in Elasticsearch?

**Comment by ChSch3000** [comment]
Finally figured out the correct configuration.

```
<filter kubernetes.var.log.containers.**>
  @type parser
  format json
  key_name log
  reserve_time true
  reserve_data true
  emit_invalid_record_to_error false
</filter>
```

![image](https://user-images.githubusercontent.com/6421265/53265000-5dbf4800-36dd-11e9-9488-c52c1b5e26a2.png)
