### ISSUE TITLE
Kubernetes certificate verify failed

### ISSUE THREAD

**Issue by TanTan-TT** [fluent/fluentd-kubernetes-daemonset#275]
Hi
When I use fluented with k8s there are some errors, detail is below
```
error_class=Fluent::ConfigError error="Invalid Kubernetes API v1 endpoint https://172.26.199.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed"
```
I believe it is because following config in ```kubernetes.conf```
```
@type kubernetes_metadata
```

According to this plugin, it can be configured with ```verify_ssl false```, but it has not environment variable for configuration. Could you add one configurable environment  variable for that? Or I make a pull request for that

**Comment by repeatedly** [comment]
> Or I make a pull request for that

patches are welcome :)

**Comment by aerostitch** [comment]
@TanTan-TT can you try with the patch from #279 please?

**Comment by cwiggs** [comment]
I'm a little confused by what is going on here.  Am I to understand that the VERIFY_SSL env variable doesn't actually work right now?

**Comment by aerostitch** [comment]
Unless I missed something, it should not yet, work out of the box, no. (see #279 ).
If you do have a custom config then you can add it there yes but for now `verify_ssl` is not yet supported.

**Comment by cwiggs** [comment]
I was actually able to get `VERIFY_SSL` to work, but I had to also make `K8S_METADATA_FILTER_VERIFY_SSL` equal false

**Comment by JnMik** [comment]
Causing me troubles as well

**Comment by gallardop** [comment]
@cwiggs where did you put the "K8S_METADATA_FILTER_VERIFY_SSL" config? I tried env vars and didn't work. Is it inside the fluent.conf?
Would you mind providing an example?
Thanks!

**Comment by Timoses** [comment]
My idea would be to simply overwrite the config in the container with a volume..

Using a ConfigMap would be a much more approachable way to customize the configuration than intransparently adding the confs in the Dockerfile.
