### ISSUE TITLE
Feaure request: Adhere to Elastic Common Schema (ECS)

### ISSUE THREAD

**Issue by osimmasgard** [fluent/fluentd-kubernetes-daemonset#292]
Hi,

are there any plans to commit to ECS in field mapping towards Elastic?  More info here: https://github.com/elastic/ecs

Thanks in advance!

**Comment by cliff-wakefield-acurus** [comment]
Would love to see this happen.

To try and do this as an individual would be too much work from my limited experience.

**Comment by holiday-sunrise** [comment]
Why is that closed ?!?
