### ISSUE TITLE
"log does not exist" errors

### ISSUE THREAD

**Issue by hkailantzis** [fluent/fluentd-kubernetes-daemonset#294]
Using fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.6, in our EFK Kubernetes stack even on minikube environment, I see multiple "log doesn't exist errors" for some pods. On our cloud environment this also happens in particular, when scaling down/up application pods: 

Elastic: 6.6.1
Kibana: 6.6.1

Sample of a log line: 
`2019-04-04 12:13:20 +0000 [warn]: #0 dump an error event: error_class=ArgumentError error="log does not exist" location=nil tag="kubernetes.var.log.containers.application-74c65d8c9-s8s9n_default_application-93f1a64981ec0df7ccd3f034c74391721b32973120b52d0a8b009a6f4ed6cc34.log" time=2019-04-04 12:13:20.261000000 +0000 record={"level"=&gt;"INFO", "thread"=&gt;"localhost-startStop-2", "class"=&gt;"WebComponentApplicationContextImpl", "message"=&gt;"Closing component application context 'log4j-logging': startup date [Thu Apr 04 12:11:21 GMT 2019]; root of context hierarchy"}`

Any hints on why this might be happening ? We're using grok-parser filter to parse our logs.
example from fluentd config below:

    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      format json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>
    <filter kubernetes.**activemq**>
      @type parser
      key_name log
        <parse>
          @type grok
          <grok>
            pattern %{TIMESTAMP_ISO8601:time} \| %{LOGLEVEL:level} \| %{GREEDYDATA:message} \| %{GREEDYDATA:class} \| %{GREEDYDATA:thread}
          </grok>
        </parse>
    </filter>
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>
    <match **>
      @type elasticsearch
      @id out_es
      @log_level info
      include_tag_key true
      host {{ .Values.service.elasticsearch.host }}
      port {{ .Values.service.elasticsearch.port.db }}
      scheme http
      ssl_verify true
      reload_connections false
      logstash_prefix fluentd
      logstash_format true
      type_name fluentd
      reload_on_failure true
      reconnect_on_error true
      with_transporter_log true
      <buffer>
        @type file
        flush_interval 10s
        retry_timeout 10d
        path /var/lib/td-agent/buffers/output_elasticsearch
      </buffer>
    </match>

**Comment by messiahUA** [comment]
Have you solved the problem? If yes - how? What's the cause?

**Comment by gbates101** [comment]
@hkailantzis I too am curious. I'm running the same versions of elasticsearch and kibana in k8s as you are, and just recently started running into this problem. Any insight would be greatly appreciated.

**Comment by hkailantzis** [comment]
If I remember correctly we solved it by putting more specific paths for the container logs at the filters. e.g:

`<filter kubernetes.var.log.containers.activemq**>`
