### ISSUE TITLE
v1.3 debian-graylog config is still using 0.x syntax?

### ISSUE THREAD

**Issue by shinebayar-g** [fluent/fluentd-kubernetes-daemonset#295]
I guess current image's [config](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.3/debian-graylog/conf/fluent.conf) file uses fluentd's [0.x syntax](https://docs.fluentd.org/v0.12/articles/input-plugin-overview)?

For example looks like these configs are not correct for [1.x version](https://docs.fluentd.org/v1.0/articles/output-plugin-overview#difference-between-v1.0-and-v0.12). (Correct me if I'm wrong, new to fluentd). 

```
   include_tag_key true
   buffer_chunk_limit 4096K
   buffer_queue_limit 512
   max_retry_wait 30
   disable_retry_limit
   num_threads 8
```

Edit: Users are expected to configure `fluent.conf` for their selves? Just noticed most of images doesn't supply default values ..

**Comment by repeatedly** [comment]
Yes, this image uses old config syntax. v1 has compat layer for configuration so this conf works.
But yeah, using v1 syntax is better.

> Users are expected to configure fluent.conf for their selves? 

If default conf is not fit for their case, users overwrite the fluent.conf via ConfigMap or build own image.

**Comment by shinebayar-g** [comment]
> Yes, this image uses old config syntax. v1 has compat layer for configuration so this conf works.
> But yeah, using v1 syntax is better.

Thank you very much for the explanation. If you don't mind, I'm going to leave this issue open for future reference.

**Comment by shinebayar-g** [comment]
Submitted PR https://github.com/fluent/fluentd-kubernetes-daemonset/pull/342
