### ISSUE TITLE
List of forks

### ISSUE THREAD

**Issue by so0k** [fluent/fluentd-kubernetes-daemonset#3]
Maybe create a list of Forks for different logging targets?

- Kubernetes to LogEntries - https://github.com/honestbee/le-k8s-ds
- Kubernetes to Loggly - https://github.com/ricardo-ch/loggly-k8s-ds

if they are all added to the Kubernetes Charts repo, end users can quickly get started using fluentd to ship to their logging service of preference.

my PR for logentries-fluentd Chart: https://github.com/kubernetes/charts/pull/779

I can do a PR with a Markdown document to list these (or add to the main README) @edsiper, what do you think?

**Comment by so0k** [comment]
I can also copy my fluentd-logentries chart to create a fluentd-elasticsearch chart for this repo and its official image, if you want?

**Comment by c-knowles** [comment]
Cool. I found the options here a bit bewildering but have just finished some config for similar but connected to stackdriver, based of this repo and the gcp image. I wonder if it would be possible to combine efforts into a single fluentd chart or whether that would end up too clunky?

**Comment by edsiper** [comment]
@so0k @c-knowles 

I think it sounds fair to try to have an unified implementation.

**Comment by c-knowles** [comment]
I think a lot of the setup would be almost identical although not sure how plugins could be managed in a neat way (without just installing all of them).

**Comment by so0k** [comment]
Like the official Docker images with sub folder Docker files and auto generated templates + different tags?

**Comment by so0k** [comment]
@edsiper has a lot of experience in that: https://github.com/fluent/fluentd-docker-image/blob/master/Dockerfile.template.erb

**Comment by c-knowles** [comment]
@so0k yes, something like that could work.

**Comment by edsiper** [comment]
@so0k actually I don't have too much experience with Dockerfiles, kudos to @tyranron who did the hard work.

**Comment by so0k** [comment]
I'll put in a PR by tomorrow morning

**Comment by so0k** [comment]
PR here: https://github.com/fluent/fluentd-kubernetes-daemonset/pull/4
