### ISSUE TITLE
v1.4 images are not available on Dockerhub

### ISSUE THREAD

**Issue by Nuru** [fluent/fluentd-kubernetes-daemonset#312]
None of the v1.4 images [listed in the README](https://github.com/fluent/fluentd-kubernetes-daemonset/blame/8c76f51/README.md#L14-L27) are available on [Docker hub](https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/tags) as of Sat May 11 17:15:00 UTC 2019

Are they available somewhere else?

**Comment by repeatedly** [comment]
See https://github.com/fluent/fluentd-kubernetes-daemonset/pull/289#issuecomment-490663708
Unfortunately, no response from docker support ;_;

**Comment by shinebayar-g** [comment]
Docker revoke all github tokens after latest security breach. You may try to reconnect docker build with github once again. @repeatedly

**Comment by repeatedly** [comment]
Rebuild image itself works.
The problem is changing Docker tags is not affected after 'save'.

I'm now considering re-create all tags for the workarounds.

**Comment by shinebayar-g** [comment]
> I'm now considering re-create all tags for the workarounds.

Uh that sounds painful. I've received email from docker hub on 4/27. This is quote from original email.

> Here is what we’ve learned: 
> 
> During a brief period of unauthorized access to a Docker Hub database, sensitive data from approximately 190,000 accounts may have been exposed (less than 5% of Hub users). Data includes usernames and hashed passwords for a small percentage of these users, as well as Github and Bitbucket tokens for Docker autobuilds. 

> Actions to Take: 
> We are asking users to change their password on Docker Hub and any other accounts that shared this password.
> For users with autobuilds that may have been impacted, we have revoked GitHub tokens and access keys, and ask that you reconnect to your repositories and check security logs to see if any unexpected actions have taken place.

Not sure if it's related to this issue tho.

**Comment by repeatedly** [comment]
I recreated all build rules and it seems works.
Existing tags still don't work but v1.4 images are available.
