### ISSUE TITLE
use Placeholders to decide the index name

### ISSUE THREAD

**Issue by yanrong1990** [fluent/fluentd-kubernetes-daemonset#313]
Hi, I want to modify the fluent.conf and rebuild the fluentd-daemonset-elasticsearch .As long as I know, we can use placeholder to define the index name dynamically ,like [https://github.com/uken/fluent-plugin-elasticsearch](url) .
so I modify the fluentd.conf  is:

```
<match log.*>
 @type elasticsearch
#  hosts XX:9200,XX9200,XX:9200
  hosts "#{ENV['ELASTICSEARCH_HOST']}"
#  port "#{ENV['ELASTICSEARCH_PORT']}"
  ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY']}"
#  target_index_key ESIndex
#  index_name 200000602_200001027
  index_name elastic.${tag}
  <buffer tag>
    @type memory
  </buffer>
  type_name system_log
</match>
```

But it will regard the index name as "elastic.${tag}" ,not variable.
Is the placeholder supported? Any mistake above?

Any suggestion will be thankful.

**Comment by yanrong1990** [comment]
have been solved 
[https://github.com/uken/fluent-plugin-elasticsearch/issues/509](url)

**Comment by roskee** [comment]
> have been solved [https://github.com/uken/fluent-plugin-elasticsearch/issues/509](url)

Hi, this link is broken. How did you solve this?
