### ISSUE TITLE
Question: Splunk HEC

### ISSUE THREAD

**Issue by porterja31** [fluent/fluentd-kubernetes-daemonset#314]
Hello my team was wondering if any of the 1.3+ verisons of the daemon set include either of the Splunk HEC plugins or if they could be added. The plugin built by splunk supports 1.3 according to https://github.com/splunk/fluent-plugin-splunk-hec/issues/33. 

Thanks.

**Comment by gliptak** [comment]
At one point

https://github.com/fluent/fluentd-kubernetes-daemonset/commit/2d67abf546e98a91155ecf69d22898c44780fee0

there was support for ```Debian``` and ```Alpine``` ```splunkhec``` daemonsets.

```splunkhec``` in particular and ```Alpine``` altogether no longer in current images directory

https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.10

https://github.com/fluent/fluentd-kubernetes-daemonset/issues/293
