### ISSUE TITLE
Logz.io v1.4 Image not published

### ISSUE THREAD

**Issue by kamirendawkins** [fluent/fluentd-kubernetes-daemonset#318]
Error:
```
Back-off pulling image "fluent/fluentd-kubernetes-daemonset:v1.4-debian-logzio-1"
```

While looking to see if I simply misspelled the tag I noticed that the image I require is not being published:
https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset

**Comment by repeatedly** [comment]
Just built the image. We missed several images for creating new rules after docker hub incident.
