### ISSUE TITLE
papertrail v1.4 not published

### ISSUE THREAD

**Issue by happysalada** [fluent/fluentd-kubernetes-daemonset#319]
image 1.4.2 shows on the [dockerhub page](https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/)
but not on the [published tags page](https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/tags?page=1)

**Comment by repeatedly** [comment]
Thanks! Just build the image.
