### ISSUE TITLE
use labels for filter output

### ISSUE THREAD

**Issue by a-hat** [fluent/fluentd-kubernetes-daemonset#330]
I would like to use the [fluent-plugin-concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat) for parsing of multiline logs. However it is a bit difficult to apply the necessary configuration, without overwriting the whole fluent.conf provided by this repository.

This is because I need to apply labels to route the events. The output has to be filtered by this label. E.g.

```
<filter **>
  @type concat
  key message
  multiline_start_regexp /^Start/
  flush_interval 5
  timeout_label @NORMAL
</filter>

<match **>
  @type relabel
  @label @NORMAL
</match>

<label @NORMAL>
  <match **>
    @type stdout
  </match>
</label>
```

Currently I overwrite the whole `fluent.conf` and duplicate the output plugin (in my case elasticsearch) to wrap it in a `<label>`, but is there a better solution? Maybe the configuration options of the docker image could be extended?

**Comment by repeatedly** [comment]
> Currently I overwrite the whole fluent.conf and duplicate the output plugin (in my case elasticsearch) to wrap it in a <label>

What is the problem? You don't want to use ConfigMap to replace existing configuration or something?

**Comment by a-hat** [comment]
Yes, it bothers me to duplicate the configuration of the es plugin.

Using `@include` seems like a good idea, however the es plugin is configured in `fluent.conf` which in turn includes the other configuration files, so I cannot include it. Also I am not sure if this works with `<label>`.

Anyway I realised that I need so set additional parameters for the es plugin, which I can do in the duplicated configuration.

Feel free to close this issue if you don't see value in making the configuration more flexible in this regards. Thanks!
