### ISSUE TITLE
No @timestamp when changed index name

### ISSUE THREAD

**Issue by rvojcik** [fluent/fluentd-kubernetes-daemonset#331]
Hi guys, 
first of all thanks much for all the work on FluenD project. 

Today I'm trying to deploy fluentd to kubernetes, to monitor logs and sending to Elasticsearch.
With default settings everything seems ok. 

I need to change index name from logstash format to `myname-write` which is alias for real index `myname-000001` and I do rollover over this.

I changed environment variables in my deployment
```
...
- name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
  value: "false"
- name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
  value: "myname-write"
...
```
FluenD start to sending logs to correct index but without @timestamp field. Propably some problem with mapping ? I'm not sure. 
I found no errors in logs.

Reason of this is I have multiple clusters, and I want to split them in multiple indices.

**Comment by repeatedly** [comment]
If you didn't change the setting of fluentd, I assume the ES side setting cause the problem.
elasticsearch plugin always set `@timestamp` by default.

**Comment by ignusws** [comment]
> Hi guys,
> first of all thanks much for all the work on FluenD project.
> 
> Today I'm trying to deploy fluentd to kubernetes, to monitor logs and sending to Elasticsearch.
> With default settings everything seems ok.
> 
> I need to change index name from logstash format to `myname-write` which is alias for real index `myname-000001` and I do rollover over this.
> 
> I changed environment variables in my deployment
> 
> ```
> ...
> - name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
>   value: "false"
> - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
>   value: "myname-write"
> ...
> ```
> 
> FluenD start to sending logs to correct index but without @timestamp field. Propably some problem with mapping ? I'm not sure.
> I found no errors in logs.
> 
> Reason of this is I have multiple clusters, and I want to split them in multiple indices.

**include_timestamp true** can be used to add @timestamp field to the logs
https://github.com/uken/fluent-plugin-elasticsearch#include_timestamp

**Comment by wrender** [comment]
I am running into the same problem. Is it possible to include_timestamp as a environment variable in the deployment?

Also, I am wondering; With the "logstash_format true" the @timestamp get's added correctly, but I can't seem to get ILM, and rollover indexes working properly. Is there any reason to actually use logstash_format true, does anyone have index lifecycle policies working with this?

**Comment by cosmo0920** [comment]
>  but I can't seem to get ILM and rollover indexes working properly. Is there any reason to actually use logstash_format true, does anyone have index lifecycle policies working with this setting set to true? I had to turn it off, and then define an index_name and use that as my index alias to get rolling indexes to work.

This seems to be a bug of fluent-plugin-elasticsearch. This issue has been fixed in https://github.com/uken/fluent-plugin-elasticsearch/pull/786. 
And this patch is included in the latest debian-elasticsearch docker image tag: v1.11.1-debian-elasticsearch7-1.3 or v1-debian-elasticsearch.
