### ISSUE TITLE
ElasticSearch + S3 image

### ISSUE THREAD

**Issue by smanpathak** [fluent/fluentd-kubernetes-daemonset#333]
I would like to configure fluentd with ES and S3 outputplugins so that ES can be used for recent log search and S3 for longer term storage. Is is possible to build an image like that as part of this project?

**Comment by repeatedly** [comment]
Yes. Installing your wanted plugin and configure to use it in the configuration.
You can see the example in the repository like https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.4/debian-elasticsearch

**Comment by smanpathak** [comment]
@repeatedly not sure I understand completely. Are you suggesting I create a separate image build for it? I know I can, but was looking for a supported image for this common use case. In that case, will this fluent repo maintain fluentd builds each with a single output plugin?

**Comment by repeatedly** [comment]
Yes. Currently, we stop to add new images. See this issue https://github.com/fluent/fluentd-kubernetes-daemonset/issues/293

**Comment by smanpathak** [comment]
Thanks, I will do the same in that case.
