### ISSUE TITLE
Graylog log level is always 1

### ISSUE THREAD

**Issue by akkie** [fluent/fluentd-kubernetes-daemonset#334]
I've successfully deployed the DaemonSet into my cluster. The logs will be shipped to Graylog, but the log level is always 1. 1 is the default level if not specified. So I assume that no level will be passed to Graylog.

https://docs.graylog.org/en/3.0/pages/gelf.html
> the level equal to the standard syslog levels; optional, default is 1 (ALERT).

**Comment by tecbird** [comment]
I've the same problem, has anyone a solution for that?

**Comment by MorleyDev** [comment]
I ran into this issue using fluentd to forward to a SEQ instance via GELF, and found adding configuration to force the default log level to info fixed this:
```
    <filter kubernetes.var.log.containers.**>
      @type record_modifier
      <record>
        level info
        cluster $cluster_label
      </record>
    </filter>
```

Can't speak for whether this is a general solution or not though.
