### ISSUE TITLE
Fluentd not sending logs to ES after a pod restart.

### ISSUE THREAD

**Issue by arunv707** [fluent/fluentd-kubernetes-daemonset#338]
Hello,

I am facing another issue with Fluentd. I have deployed `v1.4-debian` on an EKS cluster and it is set to send logs to ElasticSearch Service. However when a pod gets restarts, maybe a deployment, the fluentd stops sending logs to ES from the new pod until a restart is manually initiated on fluentd DaemonSet. All these time, it fowards logs from other pods without an issue. 

Assume you have three pods - fe, api and admin, along with the fluentd DaemonSet at 10:00 AM. You started all at once and it will work fine. In the mean time if you deleted and recreated the admin pod at 10:30, you will not get the logs after that. At this time, logs from FE and API would be forwarded to the destination without an issue. If you delete and create the fluentd pod at 10:35, the fluentd will start working and will send the logs from 10:30 and will continue doing it till a next deployment is performed on admin. The issue comes when a pod is evicted for some reason. Say if a pod admin is evicted at 11:00 AM, the log files will be wiped off from the disk and in such case, it will be impossible for the fluentd to send logs to ES.

I would like to ask:
  1. Is this an expected behavior?
  2. Do we need to restart fluentd after every deployments?
  3. If that's the case, how to detect and restart fluentd when a pod is evicted?

We are about to move to production, So please help @repeatedly 

Thanks 
Arun V

**Comment by neoxack** [comment]
same on fluentd-kubernetes-daemonset:v1.8-debian-elasticsearch7-1
