### ISSUE TITLE
how syslog should be configured to receive data from fluentd

### ISSUE THREAD

**Issue by notonlyfoweb** [fluent/fluentd-kubernetes-daemonset#341]
Hi,
I use https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-syslog.yaml with v.1.3

In the syslog-ng all I see is
Aug  5 09:23:40 syslog-7cb88f68dd-5svn8 syslog-ng[1]: Invalid frame header; header=''
Aug  5 09:23:40 syslog-7cb88f68dd-5svn8 syslog-ng[1]: Syslog connection closed; fd='21', client='AF_INET(172.17.0.14:45090)', local='AF_INET(0.0.0.0:601)'

I was trying to configure JSON parser but without luck.

Can anyone of you share the Syslog configuration?

**Comment by repeatedly** [comment]
@okkez Do you have this problem on your test?
From the error message, syslog-ng assumes octet_counting frame by default?

**Comment by okkez** [comment]
I'm not sure...
@cosmo0920 Could you take a look?
