### ISSUE TITLE
Question: cutting releases when a new docker image version is available

### ISSUE THREAD

**Issue by romoy** [fluent/fluentd-kubernetes-daemonset#344]
Could each docker version release be treated as a release and tag https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image?

**Comment by cosmo0920** [comment]
We manage each of tags in DockerHub not GitHub releases:
https://hub.docker.com/repository/docker/fluent/fluentd-kubernetes-daemonset/tags?page=1
