### ISSUE TITLE
can I force flush the file buffered or send it manually

### ISSUE THREAD

**Issue by imaemo** [fluent/fluentd-kubernetes-daemonset#346]
I have deploy daemonset in k8s, and set the buffer.
But it seems some logs are cached to buffer directory, and didn't send to graylog server.

The buffer directory is in pod, not using pvc, so if the pod is restarted, all the logs will lost,
I'm searching if there is a way to force flush the buffer, I find that I can send signal `SIGUSR1` to worker, but I can't know which is worker process
![image](https://user-images.githubusercontent.com/11534313/64751232-1e0f5f00-d54e-11e9-993a-0b5dc55b4771.png)

And because these logs can't be lost, so If I copy the buffer to external disk, can I resend these logs by other fluentd?

**Comment by shinebayar-g** [comment]
I think https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.7/debian-graylog/conf/fluent.conf#L26 this does that. Flush interval. Also afaik fluentd buffers in memory not disk by default.

**Comment by imaemo** [comment]
> 
> 
> I think https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.7/debian-graylog/conf/fluent.conf#L26 this does that. Flush interval. Also afaik fluentd buffers in memory not disk by default.

Yes, the default config is memory, but I configured it to disk, and I have configured flush interval, but looks it didn't work, the buffer size is increasing.

**Comment by shinebayar-g** [comment]
You may find some info on fluentd logs. Try increase `queue_limit_length 512` or `chunk_limit_size 8M`

**Comment by imaemo** [comment]
> 
> 
> You may find some info on fluentd logs. Try increase `queue_limit_length 512` or `chunk_limit_size 8M`

Thanks, my current chunk limit size is 18M and queue limit length is the default. And can I copy the buffer file out of the pod, restart the pod, then copy the buffer into the pod to make the new configuration take effect?

**Comment by vsinghal13** [comment]
@imaemo maybe setting the `flust_at_shutdown` param will work? The value to specify to flush/write all buffer chunks at shutdown, or not

**Comment by imaemo** [comment]
@vsinghal13 , Thanks your reply,  this param should work and I'll verify it. 
And finally I found send `SIGHUP` to fluentd process can fource flush file buffer. 
I'm using fluentd 1.0.2. The [document](https://docs.fluentd.org/deployment/signals) said send `SIGHUP` won't flush file buffer, I don't know why it actually works.
below are script to forcereload.
``` bash
pid=`kubectl -n kube-system exec ${pod} -- bash -c 'proc=$(grep -l "[E]ascii" /proc/[0-9]*/cmdline); echo $proc | cut -d "/" -f 3'`
kubectl -n kube-system exec ${pod} -- bash -c "kill -s SIGHUP $pid"
```
