### ISSUE TITLE
plugin for stacktrace/exception capturing into one line instead of broken lines in elasticsearch

### ISSUE THREAD

**Issue by shivpathak** [fluent/fluentd-kubernetes-daemonset#347]
Hi Team,

First of all it's not an issue rather request for plugin support.

Can we include [fluent-plugin-detect-exceptions](https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions) plugin to fluentd docker image?

This plugin is really good for parsing stacktrace/exceptions for many languages e.g. java, python, ruby etc.

this just needs to be added one below line in **https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/templates/Gemfile.erb** and may be some if/else clause adjustment - 

`gem "fluent-plugin-detect-exceptions", "~> 0.0.12"`

Thanks.

**Comment by repeatedly** [comment]
>  may be some if/else clause adjustment -

fluent-plugin-detect-exceptions is small size plugin, so adding it to all images no problem for me.
Could you send a PR?

**Comment by shivpathak** [comment]
@repeatedly Thanks for your response.

I just created PR https://github.com/fluent/fluentd-kubernetes-daemonset/pull/349 can you please have a look into this.

**Comment by shivpathak** [comment]
@repeatedly Thanks for merge.
