### ISSUE TITLE
"v0.12-alpine-s3" is missing on DockerHub

### ISSUE THREAD

**Issue by fhemberger** [fluent/fluentd-kubernetes-daemonset#35]
Config exists here in the repo, but the tag is missing on DockerHub.

**Comment by edsiper** [comment]
thanks for the report. Build settings fixed and image already available.

Fixed.

**Comment by fhemberger** [comment]
Cool, thanks!

**Comment by fhemberger** [comment]
@edsiper Hint: Still missing on the README. ;)
