### ISSUE TITLE
aws elasticsearch plugin supports mutiple outputs (S3)?

### ISSUE THREAD

**Issue by nareshnani529** [fluent/fluentd-kubernetes-daemonset#351]
#### Problem
Unable to send logs to AWS ES and S3 at same time and nothing shows up in logs. At this point of time would like to check AWS ES plugin will support s3?

Td-agent version : 2.5.x

Infrastructure > AWS ECS > Fluentd Aggregrators (2 instances and load balanced) > ES > Kibana

As we see some lags (5 to 6mins) in logs processing would like to check with adding other output(like s3) to view the logs. Is this right action to take?

Config :
```
<source>
        @type forward
        @id input_forward
</source>


<filter *.**>
  @type record_transformer
 <record>
    container_id ${record["container_id"]}
  </record>


<match *.**>
        type aws-elasticsearch-service
        logstash_format true
        logstash_prefix ${tag[0]}
        include_tag_key true
        tag_key "Application_name"
        flush_interval 5s

    <buffer>
      flush_at_shutdown true
      flush_mode immediate
      flush_thread_count 8
      flush_thread_interval 1
      flush_thread_burst_interval 1
      retry_forever true
      retry_type exponential_backoff
    </buffer>

        <endpoint>
                url https://vpc-xxxx.aws.amazon.com
                region us-east-1
                access_key_id "xxxxxxxxxxxxxxxx"
                secret_access_key "xxxxxxxxxxxxxxxxxxxx"
        </endpoint>
</match>
```
* OS version - Ubuntu 18.04 LTS
td-agent version : 2.5
* AWS ES version - 6.8
* fluent-plugin-aws-elasticsearch-service (2.1.0)

**Comment by ganmacs** [comment]
You want to send logs to Amazon S3 and Amazon Elasticsearch Service at the same time, right? then, could you paste the log you tried to send such a log? The config you posted seems to be only for Amazon Elasticsearch Service.

**Comment by tthayer** [comment]
I deploy two daemonsets for this, one for elasticsearch and one for s3. They function independently and don't share a configuration. The s3 fluentd log shipper will batch things up too, so you may see 10-15 minute delays before you see raw logs deposited into your s3 buckets. Keep in mind that you will need to ensure your ECS instances have IAM roles that allow them to read the bucket list and write to the destination: https://github.com/fluent/fluent-plugin-s3#iam-policy

**Comment by grv231** [comment]
Were you able to figure this one out @nareshnani529 ? I was about to make a similar setup (S3 + AWS - ES) together, then found this issue. Is it not possible to pipe logs to two targets (S3 + ES) simultaneously?

**Comment by tthayer** [comment]
@grv231 See my comment about deploying two separate daemonsets to accomplish this.

**Comment by grv231** [comment]
@tthayer Thanks for this, I was just about to edit my previous comment, mentioning I will try your approach :D. I am just surprised that this isn't possible with one single Daemonset deployment as S3/ES are plugins in fluentD.

**Comment by repeatedly** [comment]
> I am just surprised that this isn't possible with one single Daemonset deployment as S3/ES are plugins in fluentD.

You can do it by building your images to install 2 plugins. We don't want to provide such image in this repository because request never stop like "hey, I want X + Y destination. Please support!". We don't want to maintain M x N images...

**Comment by grv231** [comment]
@repeatedly Thanks for the quick reply. That makes more sense.

**Comment by cosmo0920** [comment]
This issue is multiposted and I also had answered here:
https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/58
