### ISSUE TITLE
README mentions using `ConfigMap` feature to customize config, but doesn't show how

### ISSUE THREAD

**Issue by Sushisource** [fluent/fluentd-kubernetes-daemonset#353]
Pretty much all in the title. There's quite a bit of digging involved to figure out how to actually do this properly, and just having the README demonstrate it with a simple example would be really valuable.

Thanks for your work on these images!

**Comment by ConaghFM** [comment]
How did you end up doing it? 
If I replace any files with those in /templates/conf, they throw errors during parsing and the pod fails to start (even if I have not yet edited anything in the files).

**Comment by Sushisource** [comment]
@ConaghFM I literally ended up just ripping some of the code out of this repo and recreating the image myself such that I could modify it the way I needed. No cheap tricks unfortunately.

**Comment by saltenhub** [comment]
Just in case some people are still trying to do this - you can check out this article (not mine): https://medium.com/kubernetes-tutorials/cluster-level-logging-in-kubernetes-with-fluentd-e59aa2b6093a. At the end, it is described how to mount your own `ConfigMap` containing the configuration files to the fluentd pods.

**Comment by yanivpaz** [comment]
@saltenhub , @Sushisource  following the link below:
 https://medium.com/kubernetes-tutorials/cluster-level-logging-in-kubernetes-with-fluentd-e59aa2b6093a
I suggest replacing 
```
 volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/kubernetes.conf
          subPath: kubernetes.conf
```
with 
```
volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/conf.d
```        

so you will just override the configuration
