### ISSUE TITLE
Vulnerabilities in Cloudwatch image

### ISSUE THREAD

**Issue by fgreinacher** [fluent/fluentd-kubernetes-daemonset#367]
Scanning  `fluent/fluentd-kubernetes-daemonset:v1.7.4-debian-cloudwatch-1.0` with [Trivy](https://github.com/aquasecurity/trivy) reports a ton of unfixed vulnerabilities: `Total: 228 (UNKNOWN: 0, LOW: 0, MEDIUM: 154, HIGH: 69, CRITICAL: 5)` . Unfortuantely this make is impossible for us to use this image in our production cluster (although it's working great and we’d love it!)

Are there any plans on upgrading the underlying Debian layers and/or switching (back) to Alpine?

**Comment by fgreinacher** [comment]
We’d also be open to building the image on our own, but I assume there is a reason that the Alpine-based images are deprecated. Maybe you could elaborate on what was the reason for moving away from Alpine? Thanks a lot!

**Comment by repeatedly** [comment]
We need to upgrade fluentd-docker-image before.
I created an issue for it: https://github.com/fluent/fluentd-docker-image/issues/199

**Comment by fgreinacher** [comment]
Thanks! Could you also explain the rationale for not using the Alpine version of fluentd-docker-image?

**Comment by repeatedly** [comment]
We have published debian 10 based images. Closed.

> Could you also explain the rationale for not using the Alpine version of fluentd-docker-image?

Currently, we don't have enough resources to maintain lots of images.
In addition, Alpine is different from other popular OSes.

- systemd plugin doesn't work
- jemalloc doesn't work

We are not familiar with Alpine, so we can't answer Alpine related questions.

**Comment by fgreinacher** [comment]
Alright, buster is already much better, thanks!
