### ISSUE TITLE
fluentd not saving metrics on elasticsearch

### ISSUE THREAD

**Issue by andbuitra** [fluent/fluentd-kubernetes-daemonset#396]
Hello,

I'm building an EFK stack and Elasticsearch and Kibana are up but Fluentd doesn't seem to be saving anything on ES. When requesting "/_cat/indices?v" from the ES cluster I only find references to Kibana:

```
health status index                    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .kibana_task_manager_1   GpxLvyTfTIC5yN9rPaZxGQ   1   1          2            1       33kb         16.5kb
green  open   .apm-agent-configuration gxaldbrmSTqL-ASVFfR9Vw   1   1          0            0       566b           283b
green  open   .kibana_1                YhQCrF3iR3uFWVKeOUgu4g   1   1          8            2     61.8kb         30.9kb
```

The logs on the fluentd don't seem to be saving anything (even though verbose output). This is the daemonset:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.8.1-debian-elasticsearch7-1.0
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-headless.logging.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: FLUENTD_ARGS
            value: -v
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

Any idea as of why it might be failing? Check other sources at least a "logstash_" index could be added to Kibana but I'm not able to.

**Comment by golgoth31** [comment]
Hi,
Can you provide your fluentd configuration, please ?

**Comment by andbuitra** [comment]
Hi, @golgoth31 That's all I have running. Only the daemonset.

I know is dumb but, is there supposed to be additional configuration? I assumed that mounting the logs folder to the pods while using the Docker image would be enough (this is how the DigitalOcean tutorial looks like). Isn't this correct? I have the same issue with fluent-bit.

**Comment by golgoth31** [comment]
Can you provide the fluentd logs, please?

**Comment by neoxack** [comment]
Same problem. fluentd not save logs to es 7

**Comment by golgoth31** [comment]
Well, it's possible that the default config is faulty but can you provide fluentd logs to study it, please ?

**Comment by andbuitra** [comment]
Hi, @golgoth31. This is the log:

```
    multiline_flush_interval 5s
    path "/var/log/glbc.log"
    pos_file "/var/log/fluentd-glbc.log.pos"
    tag "glbc"
    <parse>
      @type "kubernetes"
      expression /^(?<severity>\w)(?\d{4} [^\s]*)\s+(?\d+)\s+(?[^ \]]+)\] (?.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_cluster_autoscaler
    multiline_flush_interval 5s
    path "/var/log/cluster-autoscaler.log"
    pos_file "/var/log/fluentd-cluster-autoscaler.log.pos"
    tag "cluster-autoscaler"
    <parse>
      @type "kubernetes"
      expression /^(?<severity>\w)(?\d{4} [^\s]*)\s+(?\d+)\s+(?[^ \]]+)\] (?.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_kube_apiserver_audit
    multiline_flush_interval 5s
    path "/var/log/kubernetes/kube-apiserver-audit.log"
    pos_file "/var/log/kube-apiserver-audit.log.pos"
    tag "kube-apiserver-audit"
    <parse>
      @type "multiline"
      format_firstline "/^\\S+\\s+AUDIT:/"
      format1 /^(?<time>\S+) AUDIT:(?: (?:id="(?(?:[^"\\]|\\.)*)"|ip="(?(?:[^"\\]|\\.)*)"|method="(?(?:[^"\\]|\\.)*)"|user="(?(?:[^"\\]|\\.)*)"|groups="(?(?:[^"\\]|\\.)*)"|as="(?(?:[^"\\]|\\.)*)"|asgroups="(?(?:[^"\\]|\\.)*)"|namespace="(?(?:[^"\\]|\\.)*)"|uri="(?(?:[^"\\]|\\.)*)"|response="(?(?:[^"\\]|\\.)*)"|\w+="(?:[^"\\]|\\.)*"))*/
      time_format "%Y-%m-%dT%T.%L%Z"
    </parse>
  </source>
  <filter kubernetes.**>
    @type kubernetes_metadata
    @id filter_kube_metadata
    kubernetes_url "https://10.96.0.1:443/api"
    verify_ssl true
    ca_file ""
  </filter>
  <match **>
    @type elasticsearch
    @id out_es
    @log_level "info"
    include_tag_key true
    host "elasticsearch-headless.logging.svc.cluster.local"
    port 9200
    path ""
    scheme http
    ssl_verify true
    ssl_version TLSv1
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    log_es_400_reason false
    logstash_prefix "logstash"
    logstash_format true
    index_name "logstash"
    type_name "fluentd"
    template_name 
    template_file 
    <buffer>
      flush_thread_count 8
      flush_interval 5s
      chunk_limit_size 2M
      queue_limit_length 32
      retry_max_interval 30
      retry_forever true
    </buffer>
  </match>
</ROOT>
2020-01-30 23:24:31 +0000 [info]: starting fluentd-1.8.1 pid=8 ruby="2.6.5"
2020-01-30 23:24:31 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2020-01-30 23:24:32 +0000 [info]: adding match pattern="fluent.**" type="null"
2020-01-30 23:24:32 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2020-01-30 23:24:33 +0000 [info]: adding match pattern="**" type="elasticsearch"
2020-01-30 23:24:34 +0000 [warn]: #0 [out_es] Detected ES 7.x: `_doc` will be used as the document `_type`.
2020-01-30 23:24:34 +0000 [info]: adding source type="prometheus"
2020-01-30 23:24:34 +0000 [info]: adding source type="prometheus_output_monitor"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [info]: adding source type="tail"
2020-01-30 23:24:34 +0000 [warn]: #0 define <match fluent.**> to capture fluentd logs in top level is deprecated. Use  instead
2020-01-30 23:24:34 +0000 [info]: #0 starting fluentd worker pid=16 ppid=8 worker=0
2020-01-30 23:24:34 +0000 [info]: #0 fluentd worker is now running worker=0
```

Do I have to add something to the pods in order for them to be scrapped?

**Comment by andbuitra** [comment]
This is the ServiceAccount definition with the binding. Just in case it matters although if it was a problem it should throw an error

```
# This file contains the ServiceAccount definition of the fluentd agent for the fluentd DaemonSet and its permissions.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
    
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata: 
  name: fluentd 
  labels:
    app: fluentd
rules: 
  - apiGroups: 
      - "" 
    resources: 
      - "namespaces" 
      - "pods" 
    verbs: 
      - "list"
      - "get" 
      - "watch"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: logging
```

**Comment by andbuitra** [comment]
@golgoth31 did you get a chance to take a look at this? @neoxack do you still have the same issue?

**Comment by golgoth31** [comment]
Hi,
I just made the test with the latest fluentd yaml file available and all seems to be ok:
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 485
content-type: text/plain; charset=UTF-8

yellow open logstash-2019.08.31      khevX7MkQpGcyehihwTuZQ 1 1 123 0      0b      0b
yellow open logstash-2019.09.01      Kn4Fjt5MS8C9Ac2iAscziQ 1 1 178 0 126.9kb 126.9kb
yellow open logstash-2019.09.02      Dm6Vh-JxQNKQwP5Uinrgyg 1 1  35 0  38.6kb  38.6kb
yellow open logstash-2020.02.05      TMUa_9HwTu2UBORCXjtlkQ 1 1 689 0 345.5kb 345.5kb
green  open .kibana_task_manager_1   G31glgw0RfmvKWHhan2yew 1 0   2 1  43.5kb  43.5kb
yellow open logstash-2019.09.05      7jAzVswzQt6WLuQbd4wqLA 1 1   1 0  18.5kb  18.5kb
green  open .apm-agent-configuration n5W7cXzYRZKeLfaot-YsrQ 1 0   0 0    283b    283b
yellow open logstash-2019.09.06      ztzpbkefRnaDXjtbhAwtZg 1 1 170 0      0b      0b
yellow open logstash-2019.09.07      jBht6Z5OQyu2BRCkEbXeiQ 1 1  24 0  32.9kb  32.9kb
yellow open logstash-2019.09.08      y6KEl5MpT4u9FRKRHzGf3A 1 1   7 0    22kb    22kb
green  open .kibana_1                gVNIWoqzQbuI7Qbf3VWqkg 1 0   8 1  29.2kb  29.2kb

I installed elasticsearch with helm3:
helm upgrade --install elasticsearch elastic/elasticsearch

and I used this yaml for fluentd:
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch-rbac.yaml

I only changed the namespace to be in "logging" (same as elasticsearch) and elasticsearch host ("elasticsearch-master-headless")

Everything is ok

**Comment by golgoth31** [comment]
I made the test with your config file and it's ok. But I have to use the v1.8.1-debian-elasticsearch7-1.1 image as the v1.8.1-debian-elasticsearch7-1.0 is no more available

**Comment by andbuitra** [comment]
@golgoth31 I will try to deploy it again today with the new image to see if it can help. In your experience, what may cause fluentd not to log anything to Elasticsearch? Just to see if there's anything missing in my overall k8s config.

**Comment by golgoth31** [comment]
fluentd is connecting well to your elasticsearch as it founds the version (2020-01-30 23:24:34 +0000 [warn]: #0 [out_es] Detected ES 7.x: `_doc` will be used as the document `_type`.) and not logging any error so the link seems to be ok between both. Perhaps, if you have multiple elasticsearch clusters, you are lokking for the indices in the bad one. what logs are emitted by elasticsearch (kubectl logs on the elasticsearch pods)?

**Comment by andbuitra** [comment]
We only have one ES7 cluster at the moment so that wouldn't be the case. I tried to deploy the daemonset with the one you sent (just changed the namespace and the ES connection variables) and it was the same.

Nothing helpful on Elasticsearch pods sadly. I took down the cluster and started it again, then created the DaemonSet and the only thing showing up in the logs are the processes related to bringing the cluster up. 

The k8s cluster is currently running on 1.16, could that affect anything?

**Comment by golgoth31** [comment]
To ease the fluentd debug, you can get the config file form here: https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.8/debian-elasticsearch7/conf
change the lines log_level to debug and use those new files as config for fluentd.
An other problem could the reading rights on the log files. the fluentd pod is not privileged so it could have some trouble to read log files (due to bad rights, selinux or any other log hardening on the node itself)

**Comment by andbuitra** [comment]
It worked... Kinda.

I added the fluent.conf as a ConfigMap (had to set `ENV['FLUENT_ELASTICSEARCH_TEMPLATE_OVERWRITE']` to true because the "use_nil" is not valid as per the error log on the fluentd pod). And when redeployed the DaemonSet it saved logs from fluentd itself into ES and I could watch them with Kibana. However there's still no sign of the other pods themeselves as of yet. I can see the logs mounted on the fluentd's pods when accesing but they do not register in elasticsearch.

I tried to manually add the kubernetes.conf through the ConfigMap but there was no luck there. Actually, when I added it as a new "data" element on the same ConfigMap as fluent.conf it stopped receiving data completely. Not even the data from fluentd itself was showing on a freshly deployed DaemonSet. The kubernetes.conf that I used to try and override the default one is the same that was in the link you sent.

The pods I want to scrape logs from are in another namespace but I don't think that matters because I see the files themselves in the filesystem and that means it can collect them without issue. There's no selinux or other type of restrictions imposed that I'm aware of. The cluster runs on CentOS 7 VMs.

**Comment by andbuitra** [comment]
This is the output of one of the fluentd pods. After this it goes completely silent (debug is set on the configmap)

```
2020-02-07 23:10:46 +0000 [info]: starting fluentd-1.8.1 pid=8 ruby="2.6.5"
2020-02-07 23:10:46 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2020-02-07 23:10:46 +0000 [info]: adding match pattern="**" type="elasticsearch"
2020-02-07 23:10:47 +0000 [warn]: #0 [out_es] Detected ES 7.x: `_doc` will be used as the document `_type`.
2020-02-07 23:10:47 +0000 [warn]: #0 define <match fluent.**> to capture fluentd logs in top level is deprecated. Use  instead
2020-02-07 23:10:47 +0000 [info]: #0 starting fluentd worker pid=11 ppid=8 worker=0
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] buffer started instance=70095774076340 stage_size=0 queue_size=0
2020-02-07 23:10:47 +0000 [info]: #0 fluentd worker is now running worker=0
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] flush_thread actually running
2020-02-07 23:10:47 +0000 [debug]: #0 [out_es] enqueue_thread actually running
```
Nothing is being shown in the elasticsearch logs regarding this. This does show that gladly the connection is okay, the issue must be related to the kubernetes collector and/or the configuration it uses by default to scrape the logs.

**Comment by golgoth31** [comment]
Normaly, fluentd doesn't care about pod namespace as it redas directly the json fils into hostpath; can you verify that your files are where fluentd wait for them: /var/log/containers/*.log that are linked to /var/lib/docker/containers. those 2 path are defined as mounted in the fluentd daemonset yaml file.
Currently, I'm on fedora and I can see that /var/log/containers doesnt't have any link to any running containers logs.
Kubernetes module only enrich fluentd data

**Comment by andbuitra** [comment]
I checked one of the worker nodes and there's not a single container log in neither of the two relevant folders. Would it be a configuration issue whats causing this? I used `docker inspect` to check for LogPath and it show it is empty. Are we supposed to force the logs creation as a json file somehow? I thought this was the default for Docker. Also I checked the log driver and it appears to be set by default to journald.

This clearly appears to be a configuration issue in our platform rather than fluentd not working. It'd be really helpful if you could point me in the right direction here. Do we have to force it by configuring it or should it be the default?

**Comment by golgoth31** [comment]
I think it's better to change your docker's logging driver to json-file. It's the default behavior with official docker install [https://docs.docker.com/install/linux/docker-ce/centos/](https://docs.docker.com/install/linux/docker-ce/centos/). This is what you will find if you use eks from Amazon for example. The default configuration given here is to tail files. You can try to use fluentd systemd source to find your pods logs but I never use it.
Here you will find how to configure the driver to your needs: https://docs.docker.com/config/containers/logging/configure/

**Comment by andbuitra** [comment]
I changed the way it saves the logs in the docker setting (/etc/sysconfig/docker) from "journald" to "json-file" and that did the trick. With the default configuration it didn't work but I spinned up a fluent-bit DaemonSet that I had already configured and Kibana started picking up the logs.

For anyone coming across this issue that was as clueless as me: In a systemd OS, like CentOS 7+, Kubernetes configures Docker to save the logs to journald thus making the default configuration of the DaemonSet useless as there's no proper files to tail. Changing the logging driver to "json-file" globally will make the node behave like the commercial offerings (GKE, EKS) and will allow you to tail the files.

Thanks a lot for your help with this, @golgoth31

**Comment by golgoth31** [comment]
You're welcome.
This is a pure CentOS issue :) this is how centos and surely red-hat configures docker. Installing the official docker-ce package or reconfiguring the docker daemon does the job.

**Comment by andutt** [comment]
Same issue as @andbuitra on Openshift 4 and cri-o. Whats the correct volume mounts and settings to use? Using image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch. The daemonset starts fine, no errors, no warnings but now logs are being transferred to remote elasticsearch.
