### ISSUE TITLE
Fixable security issues in Ruby dependencies (Docker tag v1.8.1-debian-loggly-1.0)

### ISSUE THREAD

**Issue by heidemn** [fluent/fluentd-kubernetes-daemonset#397]
Hi,
Trivy reports the following security issues where a fix seems available.
Some of the used versions seem much older than the version that has the fix.

Is it possible to fix some of these?

![image](https://user-images.githubusercontent.com/5494429/73365495-a64b9200-42ac-11ea-9941-de5804efc965.png)

Thanks

**Comment by repeatedly** [comment]
> Trivy reports the following security issues where a fix seems available.
> Some of the used versions seem much older than the version that has the fix.

This seems false positive issue by Trivy.
Your Trivy report shows `Gemfile.lock` under bundle directory but these files are never used by users.
Trivy should ignore such non-library code under bundle/gems directory to avoid false positive.

You can see actual used version via image Gemfile.lock: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.8/debian-loggly/Gemfile.lock

**Comment by heidemn** [comment]
Thanks, good to know. 

(Why I stumbled upon this: We had used an old version of the image, where many CVEs were reported. Then I updated the image and still found these above.)
