### ISSUE TITLE
Add support for ppc64le architecture

### ISSUE THREAD

**Issue by lazystone** [fluent/fluentd-kubernetes-daemonset#407]
The official DockerHub image seems to be multiplatform - https://hub.docker.com/_/fluentd

But fluentd-kubernetes-daemonset supports only x86-64 at the moment, so it's not possible to use it in k8s cluster where nodes have different architectures. 

Would it be possible to add support for ppc64le(IBM Power)?

Are there any plans for supporting other platforms apart from x86-64?

**Comment by DanielWinks** [comment]
Similarly, arm/arm64 support would be appreciated, for clusters running on/including Arm based boards.
