### ISSUE TITLE
v1.9.2-papertrail image not published

### ISSUE THREAD

**Issue by gws** [fluent/fluentd-kubernetes-daemonset#416]
Hello,

The recent release appears to have had tags pushed for a number of other fluentd v1.9.2 images, but not [Papertrail](https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/tags?page=1&name=papertrail).

Looking at the [Docker Hub overview](https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset), the image looks like it should have been made available after the recent release.

Thank you!

**Comment by repeatedly** [comment]
Thanks for the report. Just added :)
