### ISSUE TITLE
can we have a image for windows as well?

### ISSUE THREAD

**Issue by pragadeeshraju** [fluent/fluentd-kubernetes-daemonset#423]
can we have a image for windows as well? to use it as a daemonset for windows node

**Comment by cosmo0920** [comment]
Currently, our docker building is working on DockerHub where doesn't support to build Windows docker container images.

**Comment by cosmo0920** [comment]
Duplicated of https://github.com/fluent/fluentd-kubernetes-daemonset/issues/375
Closing.
