### ISSUE TITLE
fluentd as side car container to send logs to AWS Elastic-search

### ISSUE THREAD

**Issue by farooqdevops** [fluent/fluentd-kubernetes-daemonset#439]
Hi

I have eks on fargate k8 cluster and i am using fluentd as side car container to send logs to cloudwatch. My fluentd container is able to access shared volume from application container but its unable to send logs to cloudwatch. Is there some fluent-d side-car implementation which i can use as readymade template? or if there's some other better alternative for pod logging?

BR

**Comment by syniack** [comment]
Check IAM permission and fluentd pod logs. Share logs what exception you are getting.
For reference you can check below template.

[https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluentd-quickstart.yaml]
