### ISSUE TITLE
Update to 0.14

### ISSUE THREAD

**Issue by abh** [fluent/fluentd-kubernetes-daemonset#45]
Is there a reason this isn't using 0.14?

**Comment by edsiper** [comment]
0.14 is not considered "stable" yet for production

**Comment by secat** [comment]
Do you have an ETA when 0.14 will be considered "stable" for production?

If I am not mistaken, the 0.14 version brings sub-second precision to the timestamp and this is a most needed functionality.

**Comment by StevenACoffman** [comment]
@secat Readme says Q3 2017, and here we are, so... soon?

**Comment by StevenACoffman** [comment]
[0.14.22 is a stable release](https://www.fluentd.org/blog/fluentd-v0.14.22-has-been-released)!

**Comment by secat** [comment]
@edsiper do you know when an official release of this project will be done using fluentd 0.14.22?

**Comment by StevenACoffman** [comment]
@secat This project would presumably need to be restructured to support multiple parallel versions. I made a private fork for testing over in StevenACoffman/fluentd-kubernetes-daemonset#1

Change it to reference your own private repo, and you too can be the proud owner of some fluent 0.14.22 images.

**Comment by secat** [comment]
@StevenACoffman Thank you, I will try it!

**Comment by Lawouach** [comment]
Hey all, any chance this gets some love someday? It seems 0.14 is the way to go, isn't it?

**Comment by ThomWright** [comment]
I reckon v1 is the way to go now! It's been out since December https://github.com/fluent/fluentd/releases
