### ISSUE TITLE
Rewrite_tag_filter not working as expected.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [fluent/fluentd-kubernetes-daemonset#469]
Vanilla deployment of daemonset:` fluentd-kubernetes-daemonset:v1-debian-elasticsearch` plus the following:

```
  1 <filter kubernetes.var.log.containers.ingress-nginx-controller-*.**>
  2   @type record_transformer
  3   <record>
  4     test A
  5   </record>
  6 </filter> 
  7 
  8 <match kubernetes.var.log.containers.ingress-nginx-controller-*.**>
  9   @type rewrite_tag_filter
 10   @log_level trace
 11   <rule>
 12     key kubernetes.container_name
 13     pattern /^(\w+)$/
 14     tag kubernetes.$1
 15   </rule>
 16 </match>
 17 
 18 <filter kubernetes.controller.**>
 19   @type record_transformer
 20   <record>
 21     test B
 22   </record>
 23 </filter>
 24
 25 <label @ERROR>
 26   <match **>
 27     @type file
 28     path /tmp/err.out
 29   </match>
 30 </label>
 31
```

No output results to Elasticsearch (defined under `<match **>`) 
Not errors  in pod logs.

Removal of lines 8-16 results in record `test: A` being added to event log seen in Elasticsearch.

**Comment by spyric** [comment]
I met with the same issue few days ago and only not I've solved it.
1. If you want to use nested key in record you should use `$.kubernetes.container_name` 
2. Also it will discard all logs that is not match the pattern (for your regexp, name lite "app-name" is not meet condition)
```
<match kubernetes.var.log.containers.ingress-nginx-controller-*.**>
    @type rewrite_tag_filter
    @log_level trace
    <rule>
      key $.kubernetes.container_name
      pattern /^(\w+)$/
      tag kubernetes.$1
    </rule>
    <rule>
      key $.kubernetes.container_name
      pattern /^(\w+)$/
      tag parsed.${tag}
      invert true
    </rule>
</match>
```

This config I think do that you want. Retag messages to `kubernates.NAME` and just add prefix `parsed` to prevent discarding message and cycling.

Not sure that this is the best way, but it seems to work

**Comment by andrew-pickin-epi** [comment]
Yes. I had found the need for `$.kubernetes.container_name` and hadn't come back here to update. My bad.

So for anyone else coming this way the use of nested attributes is here:
https://github.com/fluent/fluent-plugin-rewrite-tag-filter#nested-attributes

**Comment by bvamshidhar** [comment]
I'm trying to add this snippet to fluent configmap:
<match your.log.match>
  @type rewrite_tag_filter
  <rule>
    key msg
    pattern /^(?<message>.*)$/
  </rule>
</match>

May I know how to install this plugin in kubernetes daemonset?
I get this error when I run kubectl logs "podname"
{"time":"2024-04-12 03:09:12 +0000","level":"error","message":"config error file=\"/etc/fluent/fluent.conf\" error_class=Fluent::ConfigError error=\"Unknown output plugin 'rewrite_tag_filter'. Run 'gem search -rd fluent-plugin' to find plugins\""}

I was able to manually install it with kubectl exec. 
Can you please help me @andrew-pickin-epi @spyric
