### ISSUE TITLE
Cant use new exclude syntax in kubernetes.conf

### ISSUE THREAD

**Issue by loganbfisher** [fluent/fluentd-kubernetes-daemonset#47]
I am using this version `fluent/fluentd:v0.12.33` and I am not able to use the new syntax for exclude when using a grep filter.  Do you know why this is?

**Comment by ivankennethwang** [comment]
Use the latest fluentd :)

**Comment by edsiper** [comment]
@loganbfisher did you solve the issue ?

**Comment by rediculum** [comment]
AFAIK the grep filter plugin itself is missing. I tried also filtering out with grep but then the pod failed because it did not exist.
Using image fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-graylog-1.0

**Comment by repeatedly** [comment]
> AFAIK the grep filter plugin itself is missing.

No. fluentd v1 includes grep filter in the core. See docs: https://docs.fluentd.org/filter/grep
