### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by llarsson** [fluent/fluentd-kubernetes-daemonset#48]
I would love to be able to pass in SSL-related configuration to this image directly for connecting to an ElasticSearch that uses SSL.

I can imagine that I would put the certificates in a ConfigMap, mount it in, and have the certificate files available that way. But that is just part of the process, then I want to point to them via the configuration file, of course.

Or is there an easier way to accomplish this?

**Comment by edsiper** [comment]
Since this is a specific use case I'd suggest you edit the templates and add the SSL options that can be populated with the environment variables:

   https://github.com/uken/fluent-plugin-elasticsearch#clienthost-certificate-options

**Comment by prestonvanloon** [comment]
What is the appropriate environment variable for specifying the CA cert?

**Comment by repeatedly** [comment]
Currently, no such envvar: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.7/debian-elasticsearch7/conf/fluent.conf
Using ConfigMap is better
