### ISSUE TITLE
Daemonset for Azure Storage

### ISSUE THREAD

**Issue by andre2007** [fluent/fluentd-kubernetes-daemonset#482]
In the list of tags I cannot find a tag for Microsoft Azure Storage (Plugin [fluent-plugin-azure-storage-append-blob](https://github.com/microsoft/fluent-plugin-azure-storage-append-blob)).

Is my understanding correct that there is no fluentd-kubernetes-daemonset available on dockerhub supporting Microsoft Azure Storage?

**Comment by elsesiy** [comment]
Hi @andre2007, that's correct. I added this via #411 but at this point it's not clear if or when this is going to be available.

**Comment by cosmo0920** [comment]
#411 is merged and the tag `v1.11.1-debian-azureblob-1.0` is published.
Closing.

**Comment by andre2007** [comment]
Fantastic, thanks a lot.

**Comment by elsesiy** [comment]
@andre2007 Please test this and get back to me since I'm using a modified version of the underlying plugin, thank you!

**Comment by andre2007** [comment]
Currently I am between 2 releases and have to wait that the next release starts. I will test it and will come back to you. Thank you,
