### ISSUE TITLE
Preserve old images on dockerhub

### ISSUE THREAD

**Issue by marcindulak** [fluent/fluentd-kubernetes-daemonset#493]
Docker [announced](https://www.docker.com/pricing/resource-consumption-updates) that starting from November 1st 2020

```
If an image has not been pulled or pushed within 6 months, the image will be
marked “inactive.” Any images that are marked as “inactive” will be scheduled for
deletion. Only accounts that are on the Free individual or organization plans will be
subject to image retention limits. 
```

This may affect the images from https://hub.docker.com/r/fluent, and it would be great if the old images can be preserved.

In the same announcement we read:

```
If you have a Free account, you can easily upgrade to a Pro or Team account
starting at $5 per month with an annual plan.
```

This issue is created in order to know what to expect after November 1st.

**Comment by repeatedly** [comment]
@edsiper Currently, we use legacy micro plan. Does our plan have this problem?
