### ISSUE TITLE
New Fluentd image for Papertrail(v1.11.4) has not been pushed to Docker Hub

### ISSUE THREAD

**Issue by SatoruItaya** [fluent/fluentd-kubernetes-daemonset#505]
README says `v1.11.4-debian-papertrail-1.0,v1.11-debian-papertrail-1` are current stable, but the image has not been pushed to Docker Hub.

**Comment by gws** [comment]
I don't see v1.11.3 either. Possibly related to #506

**Comment by gws** [comment]
v1.11.5 is out and the Papertrail variant didn't get pushed with the other images a few hours ago.
