### ISSUE TITLE
New Fluentd image for s3(v1.11.4/v1.11.3) has not been pushed to DockerHub

### ISSUE THREAD

**Issue by bnutt** [fluent/fluentd-kubernetes-daemonset#506]
Last published image is v1.11.2, could we please get the newer images pushed to DockerHub. I looked to see if the home of the images has changed, but if not, this would be greatly appreciated!

**Comment by repeatedly** [comment]
Thanks for the report.
s3's build rules are deleted by dockerhub silently. Maybe, we hit this problem.

https://github.com/docker/hub-feedback/issues/1816

We have just deleted some arm64 image tags and restore s3 build rules. Newer images will be published soon.

**Comment by bnutt** [comment]
@repeatedly I can confirm that 1.11.4 now exists, I do not see 1.11.3, but maybe it will take some time, thank you for pushing them.
