### ISSUE TITLE
pod ip data in kubernetes_metadata.

### ISSUE THREAD

**Issue by kakarotbyte** [fluent/fluentd-kubernetes-daemonset#515]
I request to help me understand how kubernetes_metadata collects data from worker nodes and passes it. 

At the moment it looks like the below metadata is being passed. What if i want to add **pod's ip** address. Is there a way to do that ?

"kubernetes": {
        "container_name": "<REDACTED>",
        "namespace_name": "<REDACTED>",
        "pod_name": "<REDACTED>",
        "container_image": "<REDACTED>",
        "container_image_id": "<REDACTED>",
        "pod_id": "<REDACTED>",
        "host": "<REDACTED>",
        "labels": {
            "app": "<REDACTED>",
            "controller-revision-hash": "<REDACTED>",
            "pod-template-generation": "<REDACTED>",
            "app_kubernetes_io/name": "<REDACTED>"
        },
        "master_url": "https://10.100.0.1:443/api",
        "namespace_id": "<REDACTED>"
    }

**Comment by cosmo0920** [comment]
Current fluent-plugin-kubernetes-metadata_filter does not handle `pod_ip`:
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/84f66a8f9e06ab5b5211053fcce4cd8ab4bd74ba/lib/fluent/plugin/filter_kubernetes_metadata.rb#L274-L295

**Comment by cosmo0920** [comment]
Could you send your feature request into https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues?
