### ISSUE TITLE
Gemfile.lock generation broken

### ISSUE THREAD

**Issue by elsesiy** [fluent/fluentd-kubernetes-daemonset#529]
@cosmo0920 After https://github.com/fluent/fluentd-kubernetes-daemonset/pull/527 got merged, I'm not able to generate lockfiles anymore.

```
docker run --rm -i -v ./docker-image/v1.12/debian-azureblob/Gemfile:/Gemfile:ro \
		ruby:alpine sh -c "apk add --no-cache --quiet git && bundle lock --print --remove-platform x86_64-linux-musl --add-platform ruby" > docker-image/v1.12/debian-azureblob/Gemfile.lock
make[1]: *** [gemfile] Error 15
make: *** [src-all] Error 2
```

**Comment by cosmo0920** [comment]
Could you pull the latest ruby:alpine image with the following command?

```console
$ docker pull ruby:alpine
# ...
ruby                                                alpine                             9bb3098bbc3c        7 days ago          60.4MB
```

With ruby:alpine `9bb3098bbc3c` image, I can generate Gemfile.lock.

**Comment by elsesiy** [comment]
Strangely enough after pruning everything locally and fetching again it works. Would be better to use a properly tagged image but I'm unblocked for now, thanks @cosmo0920!
