### ISSUE TITLE
Create new method for versioning on Docker Hub

### ISSUE THREAD

**Issue by vikingops** [fluent/fluentd-kubernetes-daemonset#53]
Currently when new builds are created there is not a new tag created.

At this point in time the workaround is to use the `sha` (eg. `sha256:332fffdfa6b91349310b6f962f4c60801990c379566a9310f44b7b60d021830a`) to ensure that you're locked on a specific build.

My suggestion is to follow the ideas presented in this blog: https://container-solutions.com/tagging-docker-images-the-right-way/

**Comment by thomaskrag** [comment]
I wouldn't mind helping out with this if need be.

**Comment by edsiper** [comment]
make sense, any idea is pretty welcome since we are just preparing the images based on Fluentd v1

**Comment by thomaskrag** [comment]
@edsiper I'll start working on a PR for this.

**Comment by goruha** [comment]
@thomaskrag @edsiper we really need this. The case when k8s nodes have the same labeled but different byte-to-byte images makes troubles.
We catch a few issues with that already. That blocks us from using the images on production.

**Comment by repeatedly** [comment]
We want to merge similar issue to https://github.com/fluent/fluentd-kubernetes-daemonset/issues/213
If you have an idea, please post it to above issue.
