### ISSUE TITLE
Split out kubernetes config file 

### ISSUE THREAD

**Issue by GerkinDev** [fluent/fluentd-kubernetes-daemonset#531]
Hi!

For ease of maintenance and customization, it would be great to have multiple config files, one for each type of kubernetes log. In fact, in my situation, I have to override the parser for audit log (see #519), but still rely on default config for the others.

Would you welcome such refactor? 
Moreover, this could be a non-breaking change I guess, because this would be feasible to change the main `kubernetes.conf` file as an includer of each sub-file. So, if it is replaced, new includes would be omitted.

In a longer sight, this would allow more souple configuration from env. Something like this in `kubernetes.conf`

```erb
include "kubernetes-audit-#{ENV['FLUENT_KUBERNETES_AUDIT_MODE'] ||"legacy"}.conf
```

**Comment by repeatedly** [comment]
Looks good for me. Could you send a patch?

**Comment by GerkinDev** [comment]
I'll soon open a pr with this ;)
