### ISSUE TITLE
Helm chart for fluentd is not working.

### ISSUE THREAD

**Issue by apurvabhandari** [fluent/fluentd-kubernetes-daemonset#538]
Helm chart available on hub is not working. Either need to update image tagging on docker hub or update _pod.tpl and chart.yaml Ref chart: https://artifacthub.io/packages/helm/fluent/fluentd

**Comment by cosmo0920** [comment]
This issue should be reported in https://github.com/fluent/helm-charts not this repository.

**Comment by cosmo0920** [comment]
Reported in https://github.com/fluent/helm-charts/issues/84.
Closing.
