### ISSUE TITLE
Nonroot user permission issue for accessing logs

### ISSUE THREAD

**Issue by venkatjk** [fluent/fluentd-kubernetes-daemonset#548]
when fluentd securitycontext is modified to use non root user like runAsUser: 999. It changes the user but in the logs i see lot exception as below.
**[error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ rb_sysopen - /var/log/fluentd-containers.log.pos"**

**Comment by rramadoss4** [comment]
We have the same issue..
Tried below Security Context:

Pod level Security Context:
`
      securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
`
Container level security context:
`
          securityContext:
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1001
              runAsGroup: 1001
`

Looks like /var/log filesystem access for FluentD requires root user permission. However this is a security issue to allow root user permission. I have even tried with latest image version fluent/fluentd-kubernetes-daemonset:v1.12.3-debian-azureblob-1.0 but no luck..
Is there any way to workaround this issue? Any response on this will be much helpful for us....

**Comment by cosmo0920** [comment]
How about using `CAP_READ_SEARCH` capabilities for Container level security context and using together with Fluentd's Linux capability mechanism:  https://docs.fluentd.org/deployment/linux-capability

**Comment by rramadoss4** [comment]
@cosmo0920 ..Thanks for the suggestion..
Tried below capabilities..but still same issue..
Security Context at container level:
`          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              add: ["DAC_OVERRIDE","DAC_READ_SEARCH"]`

Error:
```
2021-05-17 18:20:49 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.4'
2021-05-17 18:20:49 +0000 [info]: gem 'fluentd' version '1.12.3'
2021-05-17 18:20:49 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Directory is not writable for plugin storage file '/var/log/fluentd-journald-kubelet-cursor.json'"
```

Is there anything I am still missing? If not can this issue be address in FluentD?

**Comment by rramadoss4** [comment]
Also when trying with the latest version of the chart from repo, got this error,
`Unexpected error Read-only file system - connect(2) for /tmp/SERVERENGINE_SOCKETMANAGER_2021-05-17T19:03:22Z_6
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/socket_manager_unix.rb:86:in `initialize'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/socket_manager_unix.rb:86:in `new'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/socket_manager_unix.rb:86:in `start_server'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/socket_manager.rb:94:in `initialize'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/socket_manager.rb:87:in `new'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/socket_manager.rb:87:in `open'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:68:in `before_run'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/server.rb:125:in `main'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/daemon.rb:119:in `main'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.2/lib/serverengine/daemon.rb:68:in `run'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:803:in `supervise'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:652:in `run_supervisor'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.0/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
  /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.0/bin/fluentd:8:in `<top (required)>'
  /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
  /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'`

Security context tried:
`helm install fluentdtest fluent/fluentd --set  securityContext.runAsNonRoot=true --set securityContext.runAsUser=1001 --set securityContext.runAsGroup=1001 --set securityContext.readOnlyRootFilesystem=true --set capabilities.add="DAC_READ_SEARCH" --set podSecurityContext.fsGroup=1001 --set podSecurityContext.runAsUser=1001 --set podSecurityContext.runAsGroup=1001`

**Comment by cosmo0920** [comment]
> Is there anything I am still missing? If not can this issue be addressed in FluentD?

Fluentd itself doesn't depends on `capng_c` gem which handles Linux capability?
Dis you read [the Linux capabilities on Fluentd document](https://docs.fluentd.org/deployment/linux-capability) and install `capng_c` on your image?

**Comment by cosmo0920** [comment]
@rramadoss4 And your issue is addressed in fluentd helm charts not for daemonset. Thanks for the using Fluentd.
