### ISSUE TITLE
Images for debian-syslog 1.11.5 and 1.12.0 are missing on Docker Hub

### ISSUE THREAD

**Issue by dannytranlx** [fluent/fluentd-kubernetes-daemonset#549]
Hi, thanks for reading my report.

I've been trying to fetch a more recent version of `debian-syslog`, but was unable to find the following versions on Docker Hub:
- 1.11.5
- 1.12.0

```
λ docker pull fluent/fluentd-kubernetes-daemonset:v1.12-debian-syslog-1
Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.12-debian-syslog-1 not found: manifest unknown: manifest unknown

λ docker pull fluent/fluentd-kubernetes-daemonset:v1.12.0-debian-syslog-1.1
Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.12.0-debian-syslog-1.1 not found: manifest unknown: manifest unknown

λ docker pull fluent/fluentd-kubernetes-daemonset:v1.11.5-debian-syslog-1.0
Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.11.5-debian-syslog-1.0 not found: manifest unknown: manifest unknown

λ docker pull fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-syslog-1.0
v1.11.2-debian-syslog-1.0: Pulling from fluent/fluentd-kubernetes-daemonset
Digest: sha256:59ba471abde16c756cef0611855bd7f9ed4954d67d0b0ac00252bc80b2d6d919
Status: Downloaded newer image for fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-syslog-1.0
...
```

When querying for `debian-syslog` on Docker Hub, the latest image I find is 1.11.0 or 1.11.2 from 8 months ago.
![image](https://user-images.githubusercontent.com/1034297/112910767-18db1c00-90c2-11eb-9628-867a00d85b4d.png)

My end goal is actually trying to get the `fluent-plugin-kubernetes_metadata_filter` plugin updated to 2.5.2 or higher. All other available images have 2.3.x or lower. 2.5.2 should be available on `fluentd-kubernetes-daemonset` images published after Nov. 8th, 2020 (~4 months ago).

Thank you for your help!

**Comment by MarkSymsCtx** [comment]
It would be really good if this issue could get resolved.

**Comment by cosmo0920** [comment]
debian-syslog does not built in DockerHub due to limitations for building rule definitions (up to 25).
Currently, fluentd-kubernetes-daemonset uses 25 building rules.
So, we can't build/publish debian-syslog images on DockerHub....

**Comment by MarkSymsCtx** [comment]
If that's the case then you need to edit the README.md here https://github.com/fluent/fluentd-kubernetes-daemonset and remove all references to it.

**Comment by cosmo0920** [comment]
Patches are welcome. Thanks!

**Comment by MarkSymsCtx** [comment]
You wouldn't like my patch as it would replace the README.md with
```
DO NOT USE THIS the maintainers are unhelpful.
```

**Comment by dannytranlx** [comment]
Understood, we'll build/publish ourselves then, thanks @cosmo0920 🙏
