### ISSUE TITLE
Remove fluent-plugin-google-cloud

### ISSUE THREAD

**Issue by ozayss** [fluent/fluentd-kubernetes-daemonset#553]
Hello!

fluent-plugin-google-cloud is outdated in the debian-stackdriver docker image.

Google Cloud plugin 0.4.10. 
That's a version from 2015.
It does not work anymore.

Thank you!

**Comment by cosmo0920** [comment]
Hi, thank you for your feedback.
I'm not familiar with Google Cloud Platform.

Which fluent-plugin-google-cloud plugin version did work well on GCP?
Did you try it another plugin version as custom built images?

**Comment by ozayss** [comment]
I tried to build custom image  within fluent-plugin-google-cloud 0.10.7 (latest).
It requires fluentd version 1.11.2.

I tried this configuration and looks like it works fine.

**Comment by cosmo0920** [comment]
Thanks for your reply.
We're waiting feedback and progress to be merged this PR:
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/447

Yeah, current issue is: fluent-plugin-google-cloud 0.10.7 refuses to work with Fluentd v1.12.

**Comment by cosmo0920** [comment]
The new version of fluent-plugin-google-cloud will be released soon:
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/447#issuecomment-827923571

We will publish this new fluent-plugin-google-cloud bundled image.

**Comment by ashie** [comment]
I'm considering to remove fluent-plugin-google-cloud and debian-stackdriver image completely from this repository.
Recent fluent-plugin-google-cloud sticks required fluentd version to a exactly specified version, while this repository always follow latest fluentd version. So that we never able to sync these versions.
