### ISSUE TITLE
Cannot find equivalent environment variable for "application_name"

### ISSUE THREAD

**Issue by cotjoey** [fluent/fluentd-kubernetes-daemonset#554]
Hello,

I am setting up environment variables for my fluent/fluentd-kubernetes-daemonset container and I can't seem to find what is the equivalent to "application_name".

I've tried multiple variables but none of them change the value:
```
FLUENT_ELASTICSEARCH_LOGSTASH_APPLICATION_NAME
FLUENT_ELASTICSEARCH_APPLICATION_NAME
FLUENT_ELASTICSEARCH_LOGSTASH_APPLICATIONNAME
FLUENT_ELASTICSEARCH_APPLICATIONNAME
```
Currently "application_name" defaults to value "default" and I would like to name it something else so it becomes part of my index name, i.e. logstash-fluentd-kubernetes-2021-04-01-000001 ("Kubernetes" would be the value of "application_name". Currently my index_name is: logstash-fluentd-default-2021-04-01-000001

Thank you,
Joey

**Comment by cosmo0920** [comment]
Thanks for the suggestion.
Yeah, your suggestion seems to be reasonable request.
I'll write a patch for fix this issue.
