### ISSUE TITLE
Best practices for multiple targets?

### ISSUE THREAD

**Issue by Stelminator** [fluent/fluentd-kubernetes-daemonset#56]
I would like to target both elasticsearch and stackdriver from a kops cluster on AWS.  My expected solution is to combine the fluent.conf files and rebuild the image with both plugins (and perhaps a couple more, shown below).  Is there a better way?

Additionally, I expect to run the stackdriver [logging](https://cloud.google.com/logging/docs/agent/installation) and [monitoring](https://cloud.google.com/monitoring/agent/install-agent) agents.  The logging agent is a packaged version of fluentd, so, I'm wondering if it's worth it to leave it be or try to combine that config as well as that of fluentd-gcp just to grab everything I can.

Is there an existing solution for any of this?  and/or recommendations on how I should proceed?

https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/b66ea52dce4d36c98d906518b724afd00ccf0dc1/fluentd-gcp-image/Gemfile#L7-L8
```ruby
gem 'fluent-plugin-detect-exceptions', '~>0.0.5'
gem 'fluent-plugin-prometheus', '~>0.2.1'
```

**Comment by Secathor** [comment]
Hi!
I've also the same need to send logs to both Stackdriver and ES on a GKE cluster.
@Stelminator did you find a better way than deploying a combined fluentd ?

**Comment by Stelminator** [comment]
@Secathor nope: https://github.com/Stelminator/fluentd-k8s-ds-es-sd
but it works well enough with a config file that looks like:
```
<match **>
  type copy
  <store>
   type elasticsearch
  #[snip]
  </store>
  <store>
  type google_cloud
  #[snip]
  </store>
</match>
```

You might have better luck on GKE by just deploying another daemonset and changing the `.pos` file names so it doesn't conflict with the daemonset that comes with it.
