### ISSUE TITLE
fluentd randomly gets stuck in infinite loops

### ISSUE THREAD

**Issue by wiswesser** [fluent/fluentd-kubernetes-daemonset#565]
Hello,

I recently setup an EFK stack on our Kubernetes Cluster at work, and am experiencing some issues with fluentd. At random Intervalls some of the pods start to use up all of the availabel CPU, until they notice, that they are stuck and restart. The time until they notice can be anything from 10 minutes to 5 Hours. This behaviour seems to appear completely random, since it does not happen to all 3 pods at the same time. I have attached an Image showing the spikes over the last 7 days.
![Unbenannt](https://user-images.githubusercontent.com/82935464/120769141-19a68900-c51d-11eb-9356-8c43b9ac876d.PNG)

In this Time frame fluentd does not log any messages (With the loglevel set to debug). It will simply stop until it notices the problem and logs this message:
"{"time":"2021-06-03 17:48:30 +0000","level":"info","message":"Worker 0 finished unexpectedly with signal SIGKILL"}"
And then restarts.

At one time one of the pods decided to hang whilst I was at work, giving me a chance to try and debug the issue. So I attached to the process using gdb and it looked like fluentd was trying to open a file using ppoll, failed due to hitting a set timeout of 300ms and then just tried again in an endless loop. Sadly I have no idea which file it was trying to access and given that the Cluster runs on Linux it could of course also be trying to open a network connection or something.

Configuration:
I highly suspect a Problem with my configuration file so I will include it here. This is also the reason I opened an Issue in this Repository, since I don't think this is a Bug in fluentd, because then other people would have noticed it as well. If you think this Issue belongs in a different place though, feel free to let me know.

The Daemonset Config:
[fluentd.yaml](https://github.com/fluent/fluentd-kubernetes-daemonset/files/6596848/fluentd.yaml.txt)

The fluentd Config:
[fluent.conf](https://github.com/fluent/fluentd-kubernetes-daemonset/files/6596849/fluent.conf.txt)

Current Band Aid Fix:
I have rebuild the image to add a fluentd Healthcheck plugin and added a HTTP liveness probe to the daemonset in the hopes that kubernetes will detect the pod not responding and restarting it. I have yet to see if this works. But even if it does, this of course does not fix the issue, but only the symptoms.

Looking forward to your answer

Kind Regards,
Caspar Wiswesser

**Comment by ashie** [comment]
> So I attached to the process using gdb and it looked like fluentd was trying to open a file using ppoll, failed due to hitting a set timeout of 300ms and then just tried again in an endless loop. Sadly I have no idea which file it was trying to access and given that the Cluster runs on Linux it could of course also be trying to open a network connection or something.

FYI: Maybe a different issue since it's different context though, we are now facing the following issue: https://github.com/fluent/fluentd/issues/3382

**Comment by wiswesser** [comment]
Thanks for the quick reply, this does sound similiar, I will try downgrading to v1.11 and see if that fixes it.

**Comment by cosmo0920** [comment]
I'm also reproduced elasticsearch daemonset gets infinite loop and stuck for emitting events.
This is also fluentd elasticsearch v1.12 image.
I'm using fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-elasticsearch7-1.0.

**Comment by mrnonz** [comment]
@wiswesser @cosmo0920 Let's downgrade by use docker image `fluent/fluentd-kubernetes-daemonset:v1.11-debian-elasticsearch7-1` instead.

I faced the problem like you and after downgrade its gone.

**Comment by wiswesser** [comment]
We downgraded to fluent/fluentd:v1.11.5-debian-1.0 and no further problems have occured in the past week. Thank you very much for your help.
