### ISSUE TITLE
Can't add multiple tags to Loggly logs

### ISSUE THREAD

**Issue by ZachEddy** [fluent/fluentd-kubernetes-daemonset#57]
Hi there,

I'd like to add multiple tags to logs that are sent from Fluentd to Loggly. With the current Fluentd configuration, Loggly logs are only tagged as `fluentd` and I don't have the option to add my own tags.

It would be handy to pass a collection of tags to`fluentd.conf.erb` as an environment variable via my Kubernetes YAML file — maybe something like this:
```erb
<%# -- fluentd.conf.erb -- %>

<%# current Loggly configuration %>
loggly_url "https://logs-01.loggly.com/inputs/#{ENV['LOGGLY_TOKEN']}/tag/fluentd"
<%# proposed Loggly configuration %>
loggly_url "https://logs-01.loggly.com/inputs/#{ENV['LOGGLY_TOKEN']}/tag/#{ENV['LOGGLY_TAGS'] || 'fluentd'}"
```

This seems like a useful feature and I'm happy to set to work on a pull request. What do other people think?

If you're not familiar with Loggly, [here's](https://www.loggly.com/docs/tags/) some info about tagging.

**Comment by cosmo0920** [comment]
This should be merged. Closing.
