### ISSUE TITLE
Unable to pull v1.12.4-debian-papertrail-1.1

### ISSUE THREAD

**Issue by Josh-Klassen-Dejero** [fluent/fluentd-kubernetes-daemonset#572]
When trying to pull v1.12 I get the following:

``docker pull fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-papertrail-1.1``
``Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-papertrail-1.1 not found: manifest unknown: manifest unknown``

``docker pull fluent/fluentd-kubernetes-daemonset:v1.12-debian-papertrail-1``
``Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.12-debian-papertrail-1 not found: manifest unknown: manifest unknown``

Seems to be the same as #567 and #569

**Comment by kenhys** [comment]
At least, the root cause is not as same as #569, it seems that the images are not pushed at all.

**Comment by cosmo0920** [comment]
Papertrail image build rules are dropped due to 25 build rules limits on DockerHub.

**Comment by kenhys** [comment]
It was caused by limitation, I'll close it.
Please buiild papertail image by yourself.
