### ISSUE TITLE
Fluentd daemonset not collecting application logs

### ISSUE THREAD

**Issue by aneeshcts** [fluent/fluentd-kubernetes-daemonset#574]
I have deployed Fluentd daemonset on Kubernetes cluster(centos 7.x) to capture application logs. Its not capturing any application logs. My Elasticsearch server is sitting out side of the K8s cluster and I'm using Fluentd Aggregator to send the logs to Elasticsearch. 

fluentd-daemonset-forward.yaml file as follows.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-forward-1.0
        env:
          - name:  FLUENT_FOWARD_HOST
            value: "Elasticsearch IP"
          - name:  FLUENT_FOWARD_PORT
            value: "24224"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
        - name: dockercontainerlogdirectory
          mountPath: /var/lib/docker/containers
          readOnly: true
        # When actual pod logs in /var/log/pods, the following lines should be used.
        ##- name: dockercontainerlogdirectory
        ##  mountPath: /var/log/pods
        ##  readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
      - name: dockercontainerlogdirectory
        hostPath:
          path: /var/lib/docker/containers
      # When actual pod logs in /var/log/pods, the following lines should be used.
      ##- name: dockercontainerlogdirectory
      ##  hostPath:
      ##    path: /var/log/pods

**Comment by kenhys** [comment]
Are there logs at `/var/log/containers/*.log` expectedly?

**Comment by aneeshcts** [comment]
> Are there logs at `/var/log/containers/*.log` expectedly?

Thanks Kenhys for the response. The application logs were not writing to /var/log/containers/*.log. All the logs have been pointed to STDOUT and STDERR. I have updated /etc/sysconfig/docker file with below entry and it started writing the log to `/var/log/containers/*.log`, that resolved the issue.

OPTIONS='--selinux-enabled --log-driver=**json-file** --signature-verification=false'

**Comment by aneeshcts** [comment]
I have followed the below steps.

1. Check the log-driver
#docker info --format '{{.LoggingDriver}}'

2. Update "--log-driver" section in  /etc/sysconfig/docker

3.  Reload daemon
#systemctl daemon-reload

4. Restart Docker service
#systemctl restart docker

**Comment by aneeshcts** [comment]
Issue resolved, hence closing.
