### ISSUE TITLE
Papertrail v1.13 images not pushed to Dockerhub

### ISSUE THREAD

**Issue by calebplum** [fluent/fluentd-kubernetes-daemonset#580]
`README.md` says the latest Papertrail images are `v1.13` but these images haven't been pushed to dockerhub.

```bash
$ docker pull fluent/fluentd-kubernetes-daemonset:v1.13.1-debian-papertrail-1.0
Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.13.1-debian-papertrail-1.0 not found: manifest unknown: manifest unknown

$ docker pull fluent/fluentd-kubernetes-daemonset:v1.13-debian-papertrail-1
Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.13-debian-papertrail-1 not found: manifest unknown: manifest unknown
```

Could these images please be pushed to Dockerhub?

**Comment by kenhys** [comment]
See https://github.com/fluent/fluentd-kubernetes-daemonset/issues/572#issuecomment-866522818
This is caused by limitation of docker hub.

Could you build it image by yourself, please? (not published but Dockerfile itself is still maintained)
