### ISSUE TITLE
Cloudwatch image in_tail_container_logs is duplicated Error (v1.13)

### ISSUE THREAD

**Issue by 83bytes** [fluent/fluentd-kubernetes-daemonset#584]
Hello,
I was running the latest version of the images available and noticed that the containers failed to start.

The id "in_tail_container_logs" is duplicated in `conf/kubernetes.conf` and `conf/kubernetes/containers.conf`

I can fix this. I think the original config from `conf/kubernetes.conf` should be removed ?
Or we could get rid of the `@id` field from the config present at `conf/kubernetes.conf`

**Comment by ashie** [comment]
Fixed by #585
