### ISSUE TITLE
Which Image to use?

### ISSUE THREAD

**Issue by edward-bear** [fluent/fluentd-kubernetes-daemonset#586]
Hello All,

I'm wishing to pick up logs from k8s deployments and push them to a grafana loki instance.

I'm aware of the loki plugin.

Though, what image version would you recommend for me to use for this purpose?

E.g:
fluent/fluentd-kubernetes-daemonset:v1.13.1-debian-elasticsearch7-3.0

Thank you in advance for any help

Bear.

**Comment by kenhys** [comment]
As there is no image which contains grafana loki plugin, you need to build your custom own image.
If you use fluentd-kubernetes-daemonset/ as a template, you can do it by yourself like this(maybe):

1. Add grafana-loki to templates/Gemfile.erb
2. Add image name to `X86_IMAGES` target
3. Execute `make src DOCKERFILE=v1.13/debian-grafana VERSION=v1.13.2-debian-grafana-amd64-1.0 TAGS=v1.13.2-debian-grafana-amd64-1.0,v1.13-debian-grafana-amd64-1`
4. Execute `docker build -t fluent/fluentd:v1.13.2-debian-grafana-amd64-1.0 docker-image/v1.13/debian-grafana`

**Comment by edward-bear** [comment]
hello @kenhys,

Thanks, appreciate the reply.

I have been using fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-elasticsearch6-1.1 - and executing the loki plugin on startup. Seems to work fine. 

Is there any concern using an ES image?

Cheers for any further info.

**Comment by edward-bear** [comment]
thanks a bunch @kenhys
