### ISSUE TITLE
[Features] Support for GCP Stackdriver Logging

### ISSUE THREAD

**Issue by jason-riddle** [fluent/fluentd-kubernetes-daemonset#6]
Awesome project! Any plans for logging to stackdriver on Google Cloud Platform? That could in theory deprecate this https://github.com/kubernetes/contrib/tree/master/fluentd/fluentd-gcp-image.

**Comment by edsiper** [comment]
the intention of this repository is to have an agnostic base of Fluentd to be deployed as a Daemonset for different use cases in a Kubernetes cluster. 

Stackdriver team from Google supports and maintains the fluentd-gcp-image which I think is the right thing, we should avoid to have duplicated efforts.

**Comment by jason-riddle** [comment]
Gotcha. Didn't realize Google was maintaining it themselves. Makes sense. Closing.
