### ISSUE TITLE
Use "hosts" instead of "host" in config file template

### ISSUE THREAD

**Issue by KristianLyng** [fluent/fluentd-kubernetes-daemonset#62]
References #7 

The underlying plugin supports multiple targets, but the default config does not.

I'm not sure why they differentiate between singular and plural in a config-file, but simply switching the config option from «host "$blatti"» to «hosts "blatti"» is all that's needed to make this work as expected.

As for the use case, that's simple: Avoiding single point of failure with off-cluster elk installations.

**Comment by edsiper** [comment]
which specific variable are you referring to ?
