### ISSUE TITLE
[Feature request] include HOSTNAME into static tag names

### ISSUE THREAD

**Issue by mircohaug** [fluent/fluentd-kubernetes-daemonset#64]
First of all, I have never used fluentd before so please be kind if I miss something obvious.

My setup is a multi-master setup on AWS and I want to use this DS to push all the logs to CoudWatch. The problem is that the sources defined in templates/conf/kubernetes.conf.erb include static tags like:
```
<source>
  type tail
  format none
  path /var/log/etcd.log
  pos_file /var/log/fluentd-etcd.log.pos
  tag etcd
</source>
```
This tag is used as logstream for CloudWatch and now all masters want to write to the same stream. Which leads to conflicts, provoking the error:

```
2017-11-16 16:18:23 +0000 [warn]: updating upload sequence token forcefully because unrecoverable error occured error=#<Aws::CloudWatchLogs::Errors::InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: 49576271730371018682039417059249827037114576942659553650> log_group="stage-cluster" log_stream="etcd" new_sequence_token="49576271730371018682039417229166768835589940760411130226"
```

Will a PR including the HOSTNAME env variable into all this static tags be accepted? 

I thought about something like:
```
<source>
  type tail
  format none
  path /var/log/etcd.log
  pos_file /var/log/fluentd-etcd.log.pos
  tag etcd#{ENV['HOSTNAME']}
</source>
```

**Comment by edsiper** [comment]
would you please check if some of the additional cloudwatch plugin options can help to solve the issue ?

https://github.com/ryotarai/fluent-plugin-cloudwatch-logs

**Comment by okashino** [comment]
@Ohmen did you figure this out? I have a multi-cluster Kubernetes deployment with the same issue.

**Comment by Ohmen** [comment]
@okashino No i moved to a ElasticSearch which works better with our existing tools.

**Comment by okashino** [comment]
Thanks, @Ohmen, this is where we are heading too.

**Comment by qlikcoe** [comment]
I've fixed it in my fork. Can issue a PR for this problem.

**Comment by stefanax** [comment]
@qlikcoe I'm seeing this issue and while I think it still manages to log everything it's:

A; Not pretty
B; Adding tons of noise-to-data in the logfiles.

So if you have a good solution that might help, a PR would probably not be a bad idea. ;)
