### ISSUE TITLE
Fluentd cloudwatch log forwarder for kubernetes - Problem

### ISSUE THREAD

**Issue by keithjohnhowe** [fluent/fluentd-kubernetes-daemonset#66]
I have installed the cloudwatch log forwarder and set it up to forward logs from my kubernetes cluster to cloudwatch. I have setup a log group called "kubernetes" and a IAM user with CloudWatchFullAccess. I installled using helm install --name my-release  --set awsRegion=eu-west-1
(eu-west-1 is the region os my cluster and I can access cloudwatch in this region eu(Ireland) )
 However I am not getting any log into cloudwatch. 
Is there a few steps I am missing. Do I need to login with the AWS user with a policy to access  Cloudwatch ?

**Comment by edsiper** [comment]
is Cloudwatch log forwarder based in Fluentd ?

**Comment by edsiper** [comment]
thanks for the update. closing this issue.
