### ISSUE TITLE
fluent-gem install doable?

### ISSUE THREAD

**Issue by tom932** [fluent/fluentd-kubernetes-daemonset#67]
I found a useful plugin (https://docs.fluentd.org/v0.12/articles/out_rewrite_tag_filter). 
When trying to use the plugin, I get the following error: `config error file="MY_FILENAME" error="Unknown output plugin 'rewrite_tag_filter'. Run 'gem search -rd fluent-plugin' to find plugins"`

The github-documentation states that I (might) have to install it via `fluent-gem install`.

I don't know how to install the plugin in the container.
Can I use that plugin in combination with your docker-container in a simple way, or do I have to create an own docker image, where the plugin is installed?

**Comment by edsiper** [comment]
@repeatedly isn't that plugin part of the latest images ?

**Comment by fleischer932** [comment]
@edsiper I can't find it in the `Dockerfile` of debian-elasticsearch.
I now created an own docker container as workaround.

**Comment by fleischer932** [comment]
Does it make sense to include that plugin by default? If yes, I would create a pull-request with an updated `Dockerfile.erb`.

**Comment by jhinklew** [comment]
Any progress on this? I just ran into it myself with the v1.1 debian cloudwatch image

**Comment by repeatedly** [comment]
I'm not sure but PRs are welcome.
