### ISSUE TITLE
ES Cluster value

### ISSUE THREAD

**Issue by tylux** [fluent/fluentd-kubernetes-daemonset#7]
Does the environment var FLUENT_ELASTICSEARCH_HOST support pointing to multiple ES instances? 

example:
 `FLUENT_ELASTICSEARCH_HOST : es01, es02, es03`

**Comment by edsiper** [comment]
Not directly. From a Kubernetes perspective, you should point a service by name that internally can be resolved and balanced.

**Comment by tylux** [comment]
My ES cluster sits outside of Kubernetes, does this repo have any relation to https://github.com/uken/fluent-plugin-elasticsearch?

**Comment by edsiper** [comment]
So you should point a host that can do balancing if you have Elasticsearch in cluster mode.

Fluentd uses that plugin to send events/logs to elasticsearch.

**Comment by edsiper** [comment]
oh, the plugin supports balancing.

**Comment by tylux** [comment]
yeah, I actually tried a setting aside a 4th ES node in Coordinating only mode to load balance to the cluster but then I have one failure point.

**Comment by edsiper** [comment]
question answered (balancing support)
