### ISSUE TITLE
How to collect the logs to kafka by fluentd

### ISSUE THREAD

**Issue by lijunyong** [fluent/fluentd-kubernetes-daemonset#73]

**Comment by fuusuke** [comment]
Any updates? Need a sample fluentd-kafka-daemonset yaml.

**Comment by andreacasini** [comment]
Doc says "Default YAML uses latest v1 images like fluent/fluentd-kubernetes-daemonset:v1-debian-kafka".

There is no YAML file using kafka image and no samples to start using these docker images with Kafka.

Would be useful to have a sample YAML for using with Kafka.

**Comment by couldntcatchthebus** [comment]
Is there any example for that?
