### ISSUE TITLE
Fluentd 1.0 stable support?

### ISSUE THREAD

**Issue by vide** [fluent/fluentd-kubernetes-daemonset#74]
Hello
if I understand correctly, current [fluentd stable relase is 1.0](https://www.fluentd.org/download) but the README only talks about 0.12 and there's even a revert for 0.14 being announced as the new stable in Q3 2017 (I guess it got renamed to 1.0). So, do you have any plan to update the K8S daemonset to support fluentd 1.0? What are the alternatives if I need to build a custom fluentd image with a plugin from the _fluent-plugins-nursery_ project?
Thank you very much!

**Comment by repeatedly** [comment]
duplication of https://github.com/fluent/fluentd-kubernetes-daemonset/issues/65 ?

**Comment by vide** [comment]
Didn't see that, sorry :(
