### ISSUE TITLE
container logs are not getting update continuously 

### ISSUE THREAD

**Issue by kvranjith** [fluent/fluentd-kubernetes-daemonset#77]
Hi ,
i have configured kubernetes cluster in AWS environment using KOPS.
i  have used  the below git hub (fluentd-kubernetes-daemonset/docker-image/v0.12/debian-cloudwatch/).
i am trying to send application & kubernetes logs to cloud watch through fluentd. using **fluent-plugin-cloudwatch-logs -v 0.4.0** plugin. however the application & cluster level logs stopped updating in cloudwatch within 10-15 mins. 

it doesn't work even recreating the fluentd pod.
help me to fix this issue.

**Comment by whereisaaron** [comment]
Possibly related issue and fix: https://github.com/kubernetes/charts/issues/5514
Someone else said v1.1 also fixes a similar issue.
I tried v1.2 but it just crashes (#150).
