### ISSUE TITLE
Specify an Index for ES

### ISSUE THREAD

**Issue by jmalouf69** [fluent/fluentd-kubernetes-daemonset#9]
Apologies if I missed this, but I've been trying to figure out how to specify an elasticsearch index value in the .yaml file. Is there an environment variable for that?

**Comment by edsiper** [comment]
By default the Fluentd <> Elasticsearch template uses Logstash format, this is enabled here:

https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/elasticsearch/conf/fluent.conf#L12

You can change that altering the configuration file and setting logstah format to false and adding something like:

```
index_name fluentd
type_name fluentd
```

> change your index and type names as required

**Comment by edsiper** [comment]
question answered. closing.

**Comment by marcsue** [comment]
the ref page is off =(
