### ISSUE TITLE
Unable to create the flunetd daemon on kubernetes

### ISSUE THREAD

**Issue by AnishAnil** [fluent/fluentd-kubernetes-daemonset#91]
Trying to deploy the configuration for Flunetd Daemon set and it fails with the error:

https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml

kubectl version --short
Client Version: v1.6.1
Server Version: v1.9.3-2+0b1ffe38401940

Error:

*********
kubectl create -f efk-fluentd.yaml
error: error validating "efk-fluentd.yaml": error validating data: found invalid field path for v1beta1.DaemonSet; if you choose to ignore these errors, turn validation off with --validate=false
*********

I see that the error is already logged in a few places but the solutions are not helping resolve this my deployment issue.

Any leads is highly appreciated.

Thank you

**Comment by gsaslis** [comment]
looks like your `yaml` is invalid. Please feel free to share the source.
