### ISSUE TITLE
Add Prometheus metrics support

### ISSUE THREAD

**Issue by jpds** [fluent/fluentd-kubernetes-daemonset#93]
https://docs.fluentd.org/v0.12/articles/monitoring-prometheus states that Prometheus should be used in conjunction with Kubernetes+fluentd however the Docker images from this repo do not include any support for Prometheus at all.

Can this please be added and annotations added to the daemonset?

**Comment by KYannick** [comment]
@max-rocket-internet you added prometheus, I'm currently using v1.8.1-debian-cloudwatch-1.0 of the image, should this be enabled by default? I'm not passing parameters to disable the metrics, but I'm not seeing metrics at the moment.

**Comment by max-rocket-internet** [comment]
@KYannick this was a while ago and I no longer use fluentd so can't quite remember but looking that the PR, in your container, do you have `/fluentd/etc/prometheus.conf`?
